### ISSUE TITLE
Planned phar download:

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/ImagicalMine#10]
I am planning to use AppVeyor-CI to build the phar files because it allows for MS-Powershell to be used! I will have it setup soon!

**Comment by Taki21** [comment]
ugh Genisys Staff is really disrespectful! Hate it! Betraying those miserable people...

**Comment by remotevase** [comment]
lol

**Comment by Taki21** [comment]
This is all i did:
https://github.com/iTXTech/Genisys/pull/1152

**Comment by Mike4l6** [comment]
I hope you do it today so people can stop using 10 user realms lol

**Comment by remotevase** [comment]
lol. For now, run it from the src

**Comment by Mike4l6** [comment]
can you just give me the file pls idk how to

**Comment by daniktheboss** [comment]
Ok here is the link.... even tho u won't be able to connect to the server. .. github.com/inactive-to-reactive/imagicalmine... go to clone or download and there it is! Take the src folder put it in ur imagicalmine folder and delete the old phar then run start.cmd

**Comment by Mike4l6** [comment]
its still 0.14.x

**Comment by daniktheboss** [comment]
Did u delete the old phar?

**Comment by daniktheboss** [comment]
Oh right! U have to open the branch tab and pick 0.15

**Comment by Mike4l6** [comment]
Oh..

**Comment by remotevase** [comment]
No you dont! Follow my instructions for running 0.15! LISTEN CAREFULLY, IM NOT GONNA REPEAT!
1st. Navigate to the ImagicalMine repository's master branch on github
2nd. Download the zip
3rd. Navigate to the "Extra files" repository's master branch on github
4th. Download the zip
5th. Extract both zips
6th. Combine the two folders
7th. Start the server

**Comment by daniktheboss** [comment]
It says downgrade to 0.15.0 alpha friendly update

**Comment by remotevase** [comment]
I know. I figured out the protocol. Give it a try again

**Comment by daniktheboss** [comment]
Ok

**Comment by Aplexiyy** [comment]
Hello. How can i compile the phar?? Im new to php

**Comment by Ad5001** [comment]
You don't need to, look at @remotevase tutorial !

**Comment by daniktheboss** [comment]
U delete the phar file and put the src folder in

**Comment by remotevase** [comment]
Thank you guys

**Comment by Aplexiyy** [comment]
Will it work on pocketmine??

**Comment by remotevase** [comment]
Do not use freaking PocketMine. We have our own launcher for a reason!

**Comment by remotevase** [comment]
But to answer your question: it is likely that it will.
