### ISSUE TITLE
"Not enought input type n" is back?

### ISSUE THREAD

**Issue by Ad5001** [Inactive-to-Reactive/ImagicalMine#12]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Issue description
When I'm trying to join my server with the new protocol (0.15), a forgotten error has come back to life. 

## Reproducing the issue
Just join the server

## Client information
PHP 7.0.4
ImagicalMine 1.5

## Optional information
I know that it was at first a ram error but I set the main limit to 3076MB sooo...

**Comment by ImagicalGamer** [comment]
Possibly a memory leak?

**Comment by ImagicalGamer** [comment]
@remotevase @Ad5001 http://i.imgur.com/IDWnm9E.png <-- read pic

**Comment by Ad5001** [comment]
I know that already. (That's why you see my lastest commit).

**Comment by Ad5001** [comment]
@ImagicalGamer saw 2 packets for now. They ares switching about them.

**Comment by alicheek** [comment]
so right now the new 0.15 IM software isnt fully functioning due to this protocol issue?

**Comment by ImagicalGamer** [comment]
@Ad5001 Look at steadfast2 it works for 0.15 clients

**Comment by ImagicalGamer** [comment]
The only issue is that most of the stuff was removed because it is used with LifeBoats core

**Comment by Taki21** [comment]
https://github.com/Hydreon/Steadfast2/blob/mcpe15/src/pocketmine/network/protocol/Info.php

**Comment by Ad5001** [comment]
Hum...

**Comment by remotevase** [comment]
Ho hey, Im gonna copy that file's contents and add it to this!

**Comment by ImagicalGamer** [comment]
@remotevase with your latest commit before it kicks the player it echos this in console:
1358954511
1358954511

**Comment by ImagicalGamer** [comment]
@Ad5001 This error is caused when not enough data is sent to unpack, meaning there is an issue with the packet that uses this function. Or when the data sent to unpack is incorrect

**Comment by Ad5001** [comment]
@ImagicalGamer It's my commits, I added them to see current protocol which the player join with !

**Comment by daniktheboss** [comment]
Wait your wrote this code?

**Comment by Ad5001** [comment]
The code that shows the protocol, me. The error, I dunno.

**Comment by daniktheboss** [comment]
Oh ok.

**Comment by daniktheboss** [comment]
Can you fix the problem?

**Comment by remotevase** [comment]
We will try, but as it does not crash the server, that is what shall remain until players can at least join the server

**Comment by Ad5001** [comment]
Fixed.
