### ISSUE TITLE
0.15.0 or Beta?

### ISSUE THREAD

**Issue by MCPEPluginer16** [Inactive-to-Reactive/ImagicalMine#14]
ImagcialMine is running  0.15.0 beta or Offical?

**Comment by Mike4l6** [comment]
Well it should be official

**Comment by MCPEPluginer16** [comment]
Im Offical But i cant join

**Comment by dterweij** [comment]
Thats because they are still programming as we speak. Do not expect a flawless transition. And wait a few days. Give the developers time to fix it.

**Comment by remotevase** [comment]
Thanks @dterweij wanna be one of the devs?!

**Comment by MCPEPluginer16** [comment]
0.15.1 is out !

**Comment by remotevase** [comment]
Wait seriously?! WTH Microsoft! Your doing this too darn fast!

**Comment by remotevase** [comment]
wait... No its not!

**Comment by MCPEPluginer16** [comment]
?

**Comment by MCPEPluginer16** [comment]
0.15.1 is our in GooglePlay !

**Comment by MCPEPluginer16** [comment]
Out*

**Comment by remotevase** [comment]
Since when? When was it updated?

**Comment by MCPEPluginer16** [comment]
An a hour

**Comment by daniktheboss** [comment]
It's out

**Comment by daniktheboss** [comment]
It's beta

**Comment by Mike4l6** [comment]
OMWORLD can someone just make a 0.15.x now lol

**Comment by remotevase** [comment]
no, we cant

**Comment by remotevase** [comment]
it takes a long time of testing for it to work

**Comment by remotevase** [comment]
wait a few hours

**Comment by Mike4l6** [comment]
also I did what you said and I can't join because of
[21:27:49] system> [/192.168.1.26:19132] logged out due to Login timeout

**Comment by daniktheboss** [comment]
Just wait. We are trying to fix bugs!

**Comment by remotevase** [comment]
@Taki21 supposedly got it, now we are just waiting for him to upload the changes

**Comment by daniktheboss** [comment]
Yasss!!!
