### ISSUE TITLE
OMG OMG OMG I GOT THE PROTOCOL!

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/ImagicalMine#15]
Every three hours this (1358954514) number is raised by one! This is from two hours ago! After another hour after this issue is posted, the protocol will be 1358954515! I am creating a script that will update the protocol and push the changes to the repository! Yay!

**Comment by Taki21** [comment]
YAYAYAYY!

**Comment by ImagicalGamer** [comment]
YAS!

**Comment by ImagicalGamer** [comment]
Wow!!!!!!!!!

**Comment by ImagicalGamer** [comment]
@remotevase Anything I can do to help?

**Comment by ImagicalGamer** [comment]
@remotevase gg with that but now we have new issues: Users log out to Invalid Skin, and Invalid Name

**Comment by remotevase** [comment]
what?!

**Comment by remotevase** [comment]
@ImagicalGamer how did you find that out?!

**Comment by remotevase** [comment]
Anyways, I know where the problem is

**Comment by remotevase** [comment]
See my latest commit- Protocol taken care of for the next 250 days :+1:

**Comment by remotevase** [comment]
No need for the script

**Comment by ImagicalGamer** [comment]
xD I kinda like using packet sniffing software and stuff to look in on the stuff and I got a few bugs fixed when connecting and fixed a few variables

**Comment by remotevase** [comment]
lol, i gtg

**Comment by youare1ame** [comment]
good riddance to major shit! You need to get a f*cking life! Stealing code from everyone without their permission! You stolen Converting code from mojang, and stolen a whole server code from Genysis, PocketMine, Katana, and not forgeting, you stole the attention from great projects. You have no right to do that! Thats why I will make this post to tell you that! Are you aware of your crimes to coding? This was a message, in collaberation with Anonymous! We do not Forgive, we do not forget. Expect us!
