### ISSUE TITLE
According to @ImagicalGamer

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/ImagicalMine#16]
According to him, there is now InvalidSkin and Invalid Name. Please post updates on whether you can join or not, and any console errors in here! Thanks!

**Comment by ImagicalGamer** [comment]
Those issues only occur after $timings is properly defined in Player.php on line 3304

**Comment by ImagicalGamer** [comment]
@remotevase I think this could be the root of one of the login issues:
Warning: unpack(): Type n: not enough input, need 2, have 0 in C:\Users\Jake\Downloads\ImagicalMine\src\pocketmine\utils\Binary.php on line 296

**Comment by daniktheboss** [comment]
Yea.. read my message I write on other post

**Comment by ImagicalGamer** [comment]
@remotevase Did you update support for 0.15 or 0.15.1? And @daniktheboss which are you playing on?

**Comment by youare1ame** [comment]
good riddance to major shit! You need to get a f*cking life! Stealing code from everyone without their permission! You stolen Converting code from mojang, and stolen a whole server code from Genysis, PocketMine, Katana, and not forgeting, you stole the attention from great projects. You have no right to do that! Thats why I will make this post to tell you that! Are you aware of your crimes to coding? This was a message, in collaberation with Anonymous! We do not Forgive, we do not forget. Expect us!

**Comment by remotevase** [comment]
Support for .0, gonna test .1 soon

**Comment by daniktheboss** [comment]
Um.... when I use sf2 my server name is lifeboat... in what file can we change that? Xd lol

**Comment by daniktheboss** [comment]
Ok I looked in the sf2 protocol and the protocols are 38,39,40,41,42,43,44,45,46,60,70,81?? Why do we have like 200 of them?

**Comment by remotevase** [comment]
Question 1: Please do not ask us about this in here. We are not steadfast two.
Question 2: Because SF2 has other code that is not public, and that is how it works. Therefore, we cannot figure out how it works solely from their code. Thats why we have to test it ourselves and put 2010 of them!

**Comment by daniktheboss** [comment]
Ok sorry I figured q1 by myself

**Comment by daniktheboss** [comment]
Ok, if u use the latest release and use sf2 binary... u will be able to connect but then it doesn't show your name... and also after cupple of seconds it shows "could not tick level "world": argument passed to pocketmine\level\level:addentitymovement() must be of the type array"       just to sum up to everyone where we are at

**Comment by daniktheboss** [comment]
Tell me if I'm wrong but the problem with ticking level "world" was in src\pocketmine\level\level.php on line 3503.... (array $viewers, $entityid, $x, $y, $z) but then on line 3504 it says "$motion = [$entityid, $x, $y, $z]; .... so if you add $motion on the array... it should work? Idk I just started learning php...

**Comment by daniktheboss** [comment]
Pm has updated... genisys is at a peak of update...

**Comment by remotevase** [comment]
@daniktheboss if PM had updated, then we can use their code! Gonna take a look now!

**Comment by remotevase** [comment]
Okay, I'm going to use PocketMine's updated code tomorrow to update ImagicalMine! But not fully, as we have made multiple changes so it no longer works the same way, therefore, we will edit what PocketMine did, and update it here

**Comment by remotevase** [comment]
see #22
