### ISSUE TITLE
Possible Protocol Info - And Login Info

### ISSUE THREAD

**Issue by ImagicalGamer** [Inactive-to-Reactive/ImagicalMine#17]
I have been watching a few of the other softwares chats and some packet decoder repo things and found these 2 things: https://confluence.yawk.at/display/PEPROTOCOL/Encryption <-- How it's encrypted and this https://botbot.me/freenode/mcpedevs/2016-04-16/?msg=64326116&page=1 <-- Look at shogis messages, all I read was something about a trusted server key idk

**Comment by daniktheboss** [comment]
Hmmm... interesting

**Comment by ImagicalGamer** [comment]
I got it! The login data is sent differently each time the protocol changes http://i.imgur.com/JPAfmwP.png the first login was before a protocol change with the username EmeraldGem585 the next login was after protocol change with same username

**Comment by Taki21** [comment]
Is the changes in protocol for more sharper security?

**Comment by daniktheboss** [comment]
Oh I see!

**Comment by daniktheboss** [comment]
So what do we have to do?

**Comment by daniktheboss** [comment]
So what do we have to do?

**Comment by Taki21** [comment]
i told remote vase how to auto update protocol

**Comment by Taki21** [comment]
without puting 2000 protocols lel

**Comment by remotevase** [comment]
But 2000 protocols covers all of the protocols, not just one, so if a client for some reason did not update protocol, then they would be covered by the previous protocols

**Comment by youare1ame** [comment]
good riddance to major shit! You need to get a f*cking life! Stealing code from everyone without their permission! You stolen Converting code from mojang, and stolen a whole server code from Genysis, PocketMine, Katana, and not forgeting, you stole the attention from great projects. You have no right to do that! Thats why I will make this post to tell you that! Are you aware of your crimes to coding? This was a message, in collaberation with Anonymous! We do not Forgive, we do not forget. Expect us!

**Comment by ImagicalGamer** [comment]
If any1 read what I said it encodes the packets differently each time the protocol changes.

**Comment by ImagicalGamer** [comment]
It may send skin data as a username or vice versa, or were decoding it incorrectly

**Comment by keithkfng** [comment]
Why don't we just get another extension to count, then update the available protocols in pocketmine/network/protocol/Info.php? It would probably save a lot more time than typing 2000 more protocols everytime.
If I'm wrong, excuse me, I haven't looked at the changes yet LOL

**Comment by remotevase** [comment]
@keithkfng typing that took me less than a minute in google spreadsheets (aka googles version of excel)

**Comment by remotevase** [comment]
see #22

**Comment by keithkfng** [comment]
@Inactive-to-Reactive/im-team it's good practice to lock the conversation when you close an issue. Prevents spamming :P

**Comment by remotevase** [comment]
thanks! got it!
