### ISSUE TITLE
YOU USELESS F*CKS!

### ISSUE THREAD

**Issue by youare1ame** [Inactive-to-Reactive/ImagicalMine#18]
good riddance to major shit! You need to get a f*cking life! Stealing code from everyone without their permission! You stolen Converting code from mojang, and stolen a whole server code from Genysis, PocketMine, Katana, and not forgeting, you stole the attention from great projects. You have no right to do that! Thats why I will make this post to tell you that! Are you aware of your crimes to coding? This was a message, in collaberation with Anonymous! We do not Forgive, we do not forget. Expect us!

**Comment by lolcraftboy** [comment]
why spam

**Comment by lolcraftboy** [comment]
you dont no but genisys sucks to

**Comment by lolcraftboy** [comment]
wit the cpu on 100 %

**Comment by HimbeersaftLP** [comment]
@youare1ama Shut up and go away!

**Comment by youare1ame** [comment]
It is not spam. It is informational. 
People have their opinions on what software is good or bad, but tht doesnt matter. YOU HAVE STOLEN CODE FROM THESE COMPANIES. WE (The People of the Internet) Will not stand for this any more!

**Comment by Ad5001** [comment]
No interest and in case you did not know, every software copy others. Closed.

**Comment by youare1ame** [comment]
This will never be closed. THis subject will always remain open!

**Comment by youare1ame** [comment]
no matter what heppends, this subject will always remain open until your punnishment is met

**Comment by Ad5001** [comment]
Get a life first and learn how to make a software.

**Comment by youare1ame** [comment]
We have made many softwares. Infact, we (The People of the Internet) Are the software!

**Comment by Ad5001** [comment]
-_- people like you don't have their own place on the internet

**Comment by youare1ame** [comment]
We are the internet!

**Comment by Ad5001** [comment]
@remotevase @keithkfng @Taki21 @TheDragonRing @ImagicalGamer Can someoneblock this user, I don't want my notification box spamed for sh*it

**Comment by youare1ame** [comment]
We will return, even if you block us!

**Comment by youare1ame** [comment]
We speak the truth, and nothing but! 
K3ith said  so himself. ImagicalMine is getting a bad reputation!

**Comment by HimbeersaftLP** [comment]
> We speak the truth, and nothing but! 
 K3ith said so himself. ImagicalMine is getting a bad reputation!


Stop spamming my mailbox and get back home to you mum!

**Comment by youare1ame** [comment]
I am afraid we are not children! We are one! We are the People!

**Comment by HimbeersaftLP** [comment]
> I am afraid we are not children! We are one! We are the People!

The one: The biggest noobs on earth. Haha. xD I'll just ignore you stupid little kids trying to annoy me :P

**Comment by youare1ame** [comment]
We are the People! We do not believe in childish encounters!

**Comment by youare1ame** [comment]
And we do not believe in the GitHub Emoticons to hide your comment. We would prefer if you would talk instead of hiding, like a child.

**Comment by HimbeersaftLP** [comment]
> We are the People!

* You forgot the word annoying between"the" and "people" :P

**Comment by Ad5001** [comment]
True

**Comment by youare1ame** [comment]
We do not believe in such childness.

**Comment by youare1ame** [comment]
If you persist to annoy us, then we will take action!

**Comment by Ad5001** [comment]
Tell us which softwares you've build to see if you know what the work "work" mean.
A such spammy childness is actually unacceptable. If you continue, we'll report you.

**Comment by youare1ame** [comment]
We will not reveal who we are. Through telling you our software, you will be able to identify us. That is why we will remain anonymous. And what we are doing right now is in no way against any rules, regulations, terms or conditions that GitHub supply.

**Comment by Ad5001** [comment]
At least be honest with the fact you did not code any. This is obvious. No people that coded a software would swear at people like you did.

**Comment by youare1ame** [comment]
We apologize for the rude conversation starter. One of our People was a bit over themselves.

**Comment by ImagicalGamer** [comment]
so @Ad5001 still want me to block them?

**Comment by youare1ame** [comment]
So, you still wish to block us @Ad5001?

**Comment by Ad5001** [comment]
I'll let this for this one but if this happends again, your "community account" will be banned.

**Comment by Ad5001** [comment]
Just wanted to know are you like 5 or like 100+?

**Comment by youare1ame** [comment]
We are not a community, We Are The People.

**Comment by daniktheboss** [comment]
Lol wow! At least imagicalmine works! Not like genisys! They keep on saying that they are working and fixing bugs but shows no signs of life! Imagicalmine keeps on talking to people and posting updates!

**Comment by youare1ame** [comment]
It does not matter if a software works or not. The fact remains of stolen code. It is not enough that it's stated on any document "Company_Name Fork" or "Using Comany_Name's code", stealing is stealing.

**Comment by Taki21** [comment]
Please keep your mouth quiet if u dont know anything
Before you jump to conclusions:

a) We have the right  to take codes from Genisys because of LICENSE. DO u know what a license is? No. Maybe not, so just keep quiet

b) Did you know: That Genisys takes codes from us too? AND THEY GIVE CREDIT TO US. Did u know that? Maybe not, so keep ur mouth quit

c) We are ALL the similar software in _**ONE UNIVERSAL PARTY**_

d) Did you know that all these "softwares" were forks? Maybe not, so keep your mouth quiet 

e) PLEASE DO NOT JUMP TO CONCLUSIONS or in SOME Cases be a **Hypocrite**

**Comment by Taki21** [comment]
@youare1ame Bye. No more of ur useless spam. Please get educated before making accusations period.

**Comment by remotevase** [comment]
@youare1ame For your information, we have an acknowledgement section that provides the credit for the code. Also, we always ask the developers via email or gitter or some other private form before using their code. I love teaching noobs how stuff works, which is why I am not blocking you. Well, this is how it all works. Goodbye now! Have a great year of spreading lies and rumours!

**Comment by remotevase** [comment]
If you would like guys, reread all of the posts to see the new and edited conversation

**Comment by keithkfng** [comment]
Idiots. Why didn't you use your brains and lock the conversation immediately? I really don't care about the remarks either, because it's just that person's opinion.

**Comment by remotevase** [comment]
Yes, okay. Hey, quick question. Remember the time when there were these spammers who created thousands of issues on the old ImagicalMine repo? How did you close all of them and then ban them?

**Comment by keithkfng** [comment]
Secret :P(jk)
If you go to the issues page, you'll see checkboxes. I just clicked all of them, then clicked one of the dropdown menus on the right, clicked closed, and the issues I selected were closed. As for banning, I simply contacted GitHub Support. PEMapModder told me that XD

**Comment by remotevase** [comment]
Oh, thanks @keithkfng!

**Comment by Taki21** [comment]
Wait Whaah! Really @ImagicalGamer lel xD

> Taki is Alergic to else{}

**Comment by remotevase** [comment]
@ImagicalGamer save that for the SG repo!

**Comment by Taki21** [comment]
LMAO

**Comment by Taki21** [comment]
Those I shouldve said lel! SO FUNNY

**Comment by Taki21** [comment]
Oh @keithkfng, if we locked the issue before:We would have less entertainment! Look at this guy! He is just mocking his self and it makes him look bad! Also it gets funny too seeing people mocking their lives for no reason! LOL! Locking it later is great since u have more time to see the person mocking them selves! Get it? LOL

**Comment by TheDragonRing** [comment]
:P just read through that whole thing. It was actually kinda funny, LOL

**Comment by Taki21** [comment]
yup lel
