### ISSUE TITLE
Cant Join

### ISSUE THREAD

**Issue by MCPEPluginer16** [Inactive-to-Reactive/ImagicalMine#19]
n /storage/emulated/0/Genisys/src/pocketmine/utils/Binary.php on line 296

Warning: unpack(): Type n: not enough input, need 2, have 0 in /storage/emulated/0/Genisys/src/pocketmine/utils/Binary.php on line 296

**Comment by MCPEPluginer16** [comment]
Note: i use Genisys app to run ImagicalMine ..

**Comment by daniktheboss** [comment]
Please read the open issues... close this issue

**Comment by Ad5001** [comment]
We already know this. Please read open issues.

**Comment by MCPEPluginer16** [comment]
Whats issue name?? Or number

**Comment by Ad5001** [comment]
#12 and #17

**Comment by Taki21** [comment]
Common Sense People: Are u blind? LOOK AROUND! STOP DUPLICATING!
