### ISSUE TITLE
0.15 is out!

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/ImagicalMine#2]
Protocl? Anyone?

**Comment by Ad5001** [comment]
Is the 0.15 IM branch working?

**Comment by remotevase** [comment]
No. We do not have the protocol version for 0.15 yet

**Comment by Taki21** [comment]
0.15.0 is not out

**Comment by Taki21** [comment]
Play store just has Build 1

**Comment by Taki21** [comment]
also apple didnt recieve update...

**Comment by remotevase** [comment]
Oh yeah, was rushing, didn't add enough detail

**Comment by Ad5001** [comment]
Yeah but it's better if we can have the beta working :)

**Comment by remotevase** [comment]
true

**Comment by GladiatorMine-Owner** [comment]
Fix it,it doesnt work

**Comment by remotevase** [comment]
@GladiatorMine-Owner, why thanks a lot (he says sarcastically)

**Comment by GladiatorMine-Owner** [comment]
Np

**Comment by remotevase** [comment]
Oh, god. Another cocky dude

**Comment by ImagicalGamer** [comment]
oh yay another GladiatorMine member, what are you going to steal next and try to sell?

**Comment by remotevase** [comment]
This repo, Our SG Plugin...

**Comment by Driesboy** [comment]
is there are link to download?

**Comment by Taki21** [comment]
Gonna sell poop? Like u sold my plugin without perm @GladiatorMine

**Comment by remotevase** [comment]
@Driesboy to downoad this? Look in the readme!

**Comment by Driesboy** [comment]
i mean the 0.15.0!

**Comment by Sandertv** [comment]
To download the 0.15 imagicalmine or minecraft v?

**Comment by Driesboy** [comment]
Minecraft!
Op 8-jun.-2016 07:59 schreef "Blabla" <notifications@github.com>:

**Comment by Sandertv** [comment]
https://play.google.com/apps/testing/com.mojang.minecraftpe?
Then go to minecraft and update it.

**Comment by Driesboy** [comment]
I mean apk not link to store
I dont have buy it on my andriod i use apple

**Comment by Sandertv** [comment]
Try aptoide, there's always the new versions on there and free, just search it on the internet.

**Comment by Sandertv** [comment]
I don't have the apk right now 😛

**Comment by HimbeersaftLP** [comment]
@Driesboy http://m.hiapphere.com/apk-minecraft_-_pocket_edition They have the new versions shortly after every update.

**Comment by remotevase** [comment]
@Sandertv aptoide starts at b2, almost never have b1. Been using it for years

**Comment by Mattia990** [comment]
There is the b3! 0.14.99.3

**Comment by remotevase** [comment]
I know

**Comment by Driesboy** [comment]
protocol 81

**Comment by mikelees2** [comment]
15 is out and on the play store. Does anyone have the phar file ready for it yet?

**Comment by Ad5001** [comment]
Not now please wait... @remotevase should we merge the 0.15 branch now? I will add also custom selectors soon

**Comment by remotevase** [comment]
Yes, @Ad5001 we should, but really, nothing has been done in the 0.15 branch except for testing protocol!

**Comment by Taki21** [comment]
0.15.0:
came out on:
Apple Store
Play Store
any store
u name it

**Comment by remotevase** [comment]
not amazon store yet, but in a few hours, it will

**Comment by Taki21** [comment]
amazon really?

**Comment by remotevase** [comment]
Yeah, remember there is a such thing as a kindle: fire edition?

**Comment by Taki21** [comment]
its hard to believe that exists lel

**Comment by remotevase** [comment]
From what I have found so far, the protocol should be 82

**Comment by remotevase** [comment]
Oh, oops, 92. But, there was a new packet/ many new packets that were added to 0.15, and that is why the client cannot connect!

**Comment by Taki21** [comment]
wow

**Comment by remotevase** [comment]
Ima create new issue for that
