### ISSUE TITLE
Main Chat

### ISSUE THREAD

**Issue by TheKnightGamer** [Inactive-to-Reactive/ImagicalMine#21]
Main Chat for the Developers of Inactive-to-Reactive.

**Comment by TheKnightGamer** [comment]
Could we make a new software from the start.

**Comment by TheKnightGamer** [comment]
or keep editing pocketmine to make it look good.

**Comment by remotevase** [comment]
This is simply a continuation of ImwgicalMine. ImagicalCorp originally decided to edit Pm, so we will too.
