### ISSUE TITLE
outdated client

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/ImagicalMine#22]
could not connect to server: outdated client

**Comment by remotevase** [comment]
everything else is fine. other than that, client should be able to join...

**Comment by daniktheboss** [comment]
Are u able to go to other worlds?

**Comment by keithkfng** [comment]
@remotevase Everything. https://github.com/PocketMine/PocketMine-MP/commit/ef8227a074c7acaa1c244ee4c709603c21ee1584

**Comment by lolcraftboy14** [comment]
Do tish work ???

**Comment by remotevase** [comment]
@keithkfng believe me, I tried am of thar. it's all currently implemented

**Comment by remotevase** [comment]
no, you do not even join the server! instead of saying something like "could not join server: outdated server" it says "could not join the server: outdated client". once that is fixed, I think that we will be good to go!

**Comment by MCPEPluginer16** [comment]
you are using CustomAlearts ?

**Comment by Ad5001** [comment]
Aven't the outdated client but the client just crash xD

**Comment by remotevase** [comment]
Fixed, so is the client crash, see my latest commit https://github.com/Inactive-to-Reactive/ImagicalMine/commit/86f2d93fa7e98ede3f4fef7bdd4f0dfe16f0310a
