### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/ImagicalMine#23]
I get this issue every fraction of a second
``` php
Warning: socket_read(): unable to read from socket [10054]: An existing connection was forcibly closed by the remote host.
 in C:\Users\remotevase\Desktop\OneDrive\ImagicalMine- Everything 0.15\ImagicalMine0.15\src\pocketmine\network\rcon\RCONInstance.php on line 77

**Comment by Ad5001** [comment]
Yeah, I know this error, I had same when I created the online plugin. That means or you close your server on connection or the client refreshed his page BEFORE getting the infos.

**Comment by remotevase** [comment]
2nd issue open, 1st part closed in latest commit

**Comment by Sandertv** [comment]
@Ad5001 on wiki, Latest instead of lastest :wink:

**Comment by Taki21** [comment]
New invalid rule always put this tag....

**Comment by remotevase** [comment]
Lol kk
