### ISSUE TITLE
Testing... New Issue Template

### ISSUE THREAD

**Issue by Taki21** [Inactive-to-Reactive/ImagicalMine#24]
> ## **DO NOT DELETE THE FOLLOWING**

> ### Please Provide the Issue:

> - Edit This Text To Write Your Issue!

> ### Sources:

> - ERROR: Edit This Text To Write Your Issue!

> ### Please provide all that apply to this Issue!
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is written in your native language for maximal clarity
- [ ] This issue does not have abbreveations. Abbreviations make it not understandable.
- [ ] This issue is for ImagicalMine, and not any other server software
- [ ] This is not a suggestion, but an actual issue

> ### Crashdump:

> - Edit This Text To Insert Your Crashdump

> ### Other INFO:

> - Edit This Text To Write Your Issue!

**Comment by Taki21** [comment]
@remotevase 
@keithkfng 
@Ad5001 

waht ya think about new template???

**Comment by remotevase** [comment]
it's good
