### ISSUE TITLE
Latest SRC Build, Server Crash and Client Crash

### ISSUE THREAD

**Issue by alicheek** [Inactive-to-Reactive/ImagicalMine#26]
Using latest SRC folder and i get this crash after some one logs in, client still gets crashed out also 

ImagicalMine Crash Dump Fri Jun 17 10:59:21 CEST 2016

Error: Argument 1 passed to pocketmine\Player::dataPacket() must be an instance of pocketmine\network\protocol\DataPacket, instance of stdClass given, called in /home/minecraft/mcpe/src/pocketmine/entity/Human.php on line 307
File: /src/pocketmine/Player
Line: 1079
Type: notice

Code:
[1070] 
[1071]     /**
[1072]      * Sends an ordered DataPacket to the send buffer
[1073]      *
[1074]      *
[1075]      * @param DataPacket $packet
[1076]      * @param bool       $needACK (optional)
[1077]      * @return int|bool
[1078]      */
[1079]     public function dataPacket(DataPacket $packet, $needACK = false) {
[1080]         if (!$this->connected) {
[1081]             return false;
[1082]         }
[1083] 
[1084]         $timings = Timings::getSendDataPacketTimings($packet);
[1085]         $timings->startTiming();
[1086] 
[1087]         $this->server->getPluginManager()->callEvent($ev = new DataPacketSendEvent($this, $packet));
[1088]         if ($ev->isCancelled()) {
[1089]             $timings->stopTiming();

Backtrace:
#0 /src/pocketmine/Player(407): pocketmine\entity\Human->spawnTo(pocketmine\Player Player(12))
#1 /src/pocketmine/Player(940): pocketmine\Player->spawnTo(pocketmine\Player Player(12))
#2 /src/pocketmine/Player(888): pocketmine\Player->doFirstSpawn(boolean)
#3 /src/pocketmine/Player(1958): pocketmine\Player->sendNextChunk(boolean)
#4 /src/pocketmine/Server(2872): pocketmine\Player->checkNetwork(boolean)
#5 /src/pocketmine/Server(2537): pocketmine\Server->tick(boolean)
#6 /src/pocketmine/Server(2393): pocketmine\Server->tickProcessor(boolean)
#7 /src/pocketmine/Server(1971): pocketmine\Server->start(boolean)
#8 /src/pocketmine/PocketMine(519): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft/mcpe/, string /home/minecraft/mcpe/, string /home/minecraft/mcpe/plugins/)

ImagicalMine version: 1.5 #0 [Protocol 81; API 2.0.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux ns3015265.ip-51-254-44.eu 3.14.32-xxxx-grs-ipv6-64 #6 SMP Wed Jan 20 17:52:44 CET 2016 x86_64
PHP Version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
BenchMark 1.0-Alpha by hm for API(s) 1.12.0, 1.13.0, 2.0.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
ItemCloud 1.3 by onebone for API(s) 1.4.0
xRulesx 1.0.0 by xFlare for API(s) 1.8.0
CraftingTableFix 2.0-Alpha by hm for API(s) 1.13.0, 2.0.0
SimpleAuth 1.7.2 by PocketMine Team, shoghicp for API(s) 2.0.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ChatDefender 1.1.1 by Falkirks for API(s) 1.6.0
EconomyUsury 1.0.1 by onebone for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
PeacefulSpawn 2.5 by LDX for API(s) 1.0.0, 2.0.0
MoreTrees 1.0-Alpha by hm for API(s) 1.12.0, 1.13.0, 2.0.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWwlvG0eW/is1tLEjBWzeFCUGyowiS4kzPriWvB4gDIxid5HsqK90dYtisv7v+71X1RcpJfKx
yC4QIYG7rlfvPqqKv7UyP1StaX90dNQfD0+O+u1WIHV2kaZx2pr+1sq2CYZbUZz5rmq1W6HSWq6o
6yxd5aGKMtEXidRaeSKLRRK7NyoL/UjN57NAblU6nXoykzNJ/QeHIsx1JhZKyEj4kc5k5CoRLxvr
IpVt4vRmPk/SOIvdOJjPn5Ug2o1lOvPOga4WK/9WRW3hyiAAIn4kuus4VF0C6KZymXVDN1Fdnbrd
aqcukPezbff7PJRRJ1knIo5EgAEx7E1A6jIPgks/IFofA82QS3BorV137xyM0zbgem9y0m5lqQRr
pz+2nvTE/QsORr3J4bTBJIP7fM7IO9/oRG6i6/hgn//CgugPDg+x8ZP+Q3ucjHo7e5iBjwE+eAj4
8fHxA8C9+NJPdXZFexws4jhQMmJYw4dg9U/GDwHTKvJeqbvsfJ1HNw1ooz1oVyq9BbTB8WTwADR3
rdybV0YbG8DGDwIbD3cFZUacb2A/TSBHDwIZngx/B8gsjV0YYZw2oE0egtY/mfQfgAY7SrMGlON9
nvPnS3wejPsnDwB6/96NYZVp7mYNJTmPw0Rm/iJQbKUvYulBZ+LFz8qFIddn5pkf6Pn8pfSjF/Fq
VZsFsH60ut+eP2c0CfIVXEn3sPXTh3ZL/eXvPsJngWGGfa3pUgZatVtu7CliH0Z7gIHZ+OrjS+Cv
+9VXpmNgO8RX4gqWqokrcQqdAA0VycTXbK0EGbNY5Msl747lw3K5aY922uMK/D8TmcqwDvRpwv+a
mUd7M8kKhPl7GinlnZ3/SxzESebHkQwOzapJbVWqsjwlmWb/TUvNhONyQtd0nNiOJF8EviuWeeQS
RFFTkX0U2xUGp4L5eyh+Y3jHvWID/PlLcfC3p9na1/BUcQTBZ8orZ/ZrM+nP4svgvjZTBrUpH0zX
sJDd8ag2+BQ5AuxIA51r8zWdrlRGIqywtyMHlohDu8n4HjjW85gVB8XMo3LvSWMNE6itp8G2M9a8
lzKCWaYHhyAeRnABc8gOnqpb4BipTU3whKUdJVDtgsuHxb7HOzwFEOcbX5+TzZF1HRyWTD3ZYWqd
oDip6PnwV1D/K6j/FdT/1KDebq1UpFIZUFgCQRp+F+bb74zBk0XuB15r2kMcszG3NT1G6SMTH3MG
nV6nh1krP0Or98g/LEjlTeAvaE3nmCHkkaTqqvXCj/I7Eelhrz8eHI07fuKM+85gPHJGo47KxbDT
H3WGA+cOf84q1Y6f3B45RyMBhbp6ORPvECB/QLAc9ER/Mh0PpqOROL+4Rrt/JO6Oj94fjbAblR7T
1gTYD9D6FWaD5tASg8H3sS5wQQc3Am6U8VwTsy4g9zjczq7WcUJtS0Oju11j6cBuKPNsHaeanF4c
qQX+JykwS38E3/uYRx0qktAdoAbVQubgqYRSAczBmI6X2bN6RygpySjgwUMaJBINJObzHZQCqCIm
z15fXb97/ebFM3Rt1EL7GdCPUMyBTLvih3ixTxl17tI1+mO6DHtBn/13UP7b53+Htj207ZFtj9D+
Quz4OV6UzDBUPIIVszxVM5WGusaJqq/dsJlhZ9JkxNHo8rLXE/8h4LjIpJ9HSz9C7GpK3JBuzOkT
SX1vdoL/LlCrff4Boa11liV62u3CkNf5ouPGYZfXWi9RwQE7vlWRu34p05saO6q+Jjt6zlmQrGWT
JetwX93bX4gL/jJTMpzPS4Rqn4+UNvvl73KZenV513qbqt9nba2R97LwtCr9YfaqSepnUNYEC9k2
MPpY6TahdWvAuiTj55kKz4M4r7Og6ttR+T+2/NEXcGggJXRpexMnOaQ+hnDQbWF0wiru/cN8nJZQ
ieq7N3mg9F2N5qJnR6tZT2s0310GMm2SfPzpJBto87nd3ND7OOU9J5Ei6F/Trpd+nZS9oR0P/hhL
/QIGuosG0qR9xB5B6ZUfJoE6A641GmudTYlNduNuldiJazgMDCJQrta+m9Qo/ixCK1yQKdbxssRd
XZ+9uX47+0M3XCLarUGhgxitqQpCmXo9q7Gg0d1kQn9Hbb9UzlHfEpG2icAjROkjNGYIjeZcydJR
66xTgdxg0ZTki2f/bijpyefrKEDC35QIPMoA75Md4Dgvz2cX3RoxoPe/8P1GbZoBptbZpHcvZdwl
2MbPz6e4QuHxFIPgWyxLeVmHSgt42VaVP57Nnu/nj9S5mz+e/L/IH4FLmT8aKh7jlNcSwJcAruoa
3ujetdSdnOJSBjd+eqMb/Dj6dHkvLbz53AUWnsUCvriJ0+PrhLc6T7f7kjbdu9Gz/wVqoLoufYQA
c0KoFGGB3iPo/DbFHFfqrCHDeu+OCI+aRF7cxsEVkPxilV5t611zfSi0wFg3m01HARWC2sluyFJn
SrpqmQd8BlVPeRv9NeoGnfHvOqTeF/JHDQQ+3wk36QHhL+NUXadK1eu6qu9PLmRKREB4DafHW+SV
CoJ9g+TeXd87+fPsUQOf0hwtco+n8YWMvH0aufcT4sv/Fo0B8ClptMh9hBzvPVy692zpz5Rj/Zjp
8adMVUr7vQqShmvdG/qDEycZ+Hmw/Uhiayn17xBrQM/na0bkkz2RDNTPkH4aA1ztkNkpatIMNt4N
2aN396ivFOJa3u3rA3XuMmj456VUn6hFmbwrlchQ9MjjOcpbdk7nuKvpxEe7dbs5Mvu0Grd2BLhH
IfI1vr7UyPsB7N/q1o9zPbtwiv7WA+d2hHT19QVO7RjMBzq2pstbBdUq4g5fXnSSNIZ2ZT4FwdaT
WdkS53G09FeCrrrn6Tx6cpn64oc8Ev2J6Pem45Npjw7Wr8zJOs0I48w7/Tb1VUrLa/W1uSYRSPvG
nR7NtFeUSZxmp/2T/nBAnZs1aHICX2en8XJJPTKK4jxyyT74Qkq6a1/dKnpZoE/jiCFRKHcSU1yB
r6cMP1WezqBWjisDNw8kj1igobyz8PRpv8fTZRDEG2cZ+Kt11oArIz9EGdvoC+NF0bECP8PYU2bT
ZZwC1bLPbrdGVeQifBft5Daxqz1/ufSBXbY97TM0voNBheholdFxiD6l7gAUBw6p9ekmTgOv6tNK
ebUp9Bzj9NnF5dnbF9fUa/TW+SVX6dZuabtSt2IHfXfokQaAe6df8R84kmexo+WtKnHVvDKIV6QP
xWK6Kym9WGcbBqRCgpyjcFl78pR5z0okwCDxPJQrH1IhvYBOieu10vR8wRAsZKr4PQNkp/EhM+GS
EvCzED9yg9wzTzj2dJdgXcUhv/zI9mFquVRtEWMk1QRSLFIlb8Q2zlMLi+6zITd/6fMOEFkKjYLP
B+BXalOC66JUkhCaFps4+nsmZJIomQpiWAha6YJ9S49F6ALdkL1Zq0jkySqVHgB05hHpvwE2nUfi
yfUaXt8J0AUskCmscrlSgl6JMMesrWgf7SAGfP9X5iktPacLWkNFcyEQKFyDijob/8ZPlOfLTpyu
utTqvoCZvY+X759fvX5/NDxxBu9pHdhYApqKOVzfat6ijd6tFfGOnpvwUxNQaS8XIaZURho2Zl75
WG4ypsADX/RKBSL14AJdJdaIfwELOQRgYzPVlvzmAv16nWdeTNZm3hQRMtaLvFF8bYut/2ZwOyPr
FeQ36K7ThlJx60vxn6T6mMImUATZqSA/TguRpGyEJE3VMVCyWxl5SQtI5BqaCJ8PbWASEc8wE/HD
I2ZVAw5wW8RaVeAv2NgKOBt4aNar4kaYIc2jRt8+jk0g4J0gZyKg+NAtonexFVYjMd3adzlaMfTJ
Ox8iiyMop/Q8kSptdJhopUt10CRRCrNvFdDchSKmQnzql1wGJFh+RiVuZZArcWC3hOs/BHCzH/yK
Io/uQC/oBnuKUdr5VR4u6D57Kc70NnKvpb4R9KIAptih8bf0Pow0vSCSZq1TpAA5lAuzdVuw5xPW
Q0L524KYBioosjNbEBOpL8wj2CBNYdhXrHygB2aaxnfw5pkCC0AOG01UokZcNeg8X5Kt0xSy6bbw
s7+Dc1nKqzxFcYb1eWetOAAFUBYxII4wDY6lcsqQyO4pNKRbtvrvgngBxlLWIEw3VDj0M/JuoVrJ
xTYDQuLKoNLjzY0TNj4DNG18RoyZLSiCGTgF/zXzZemn/KJO0bsegrKEtyl2NOIHMTlr/ioGHTEZ
GfEM+6wYSYcRm4renJ0Ou/cMTkt6/8fRp/zqd5Cn0PxZyNNLJvv8jl1TiY+FpgVMyjyALLChPQuU
hr3ByGCFJNKPObCRLWrakN/eFNiV9tbHVvBXHukYz3BgD8pYGgeEOIIXhIWCb+QdHmKrYScyroBj
Bdm6mTbnyE0wYH2VJRt3RDu8JhdCsZKnd/YnE9k2ZQYLE+VSSNXMFsLV8NisLQkAJ1WiKzKHPUun
PrwXIUv10FC9kukC8nfcOAhMFkgWdi9XWZ0IFbtG2DWw3VBGOQfvOhbIa3LowmG78Ak7ymC1wfjV
5bLwDWGlZR3x2kRObkEj1nEeeCUiPjzIJhIV6qS3ImHMQeBRr2doFE8u2RL2fCPrilldErVM47Bw
sbTWjjt1r1STKYiwottVhXv0p7aOMmmXHpppw+8XrPXkELmTMKPihagRJuNus3mmSGW0meRQNkFZ
UQWLQBVitoZycmTxfBabZbvioyBAOZdZVodgdrHTvgDNHIhQVkB3DdVFZmw3ooEyev8uqHlkHzOX
SSBUIzCRcCEzlDqUzfD7S00vm4X1SmyAJsW1o8YZLVQZE9ndPKm7r2KEDD/dZgS7LZx+TZkp9vG2
TlagArcyPjJepYq1XGtQoPOMu7MCNGvRaXHqiO9RTYG9p8iqobjns7dtrAUGC/ifje8hG2KvzfZd
gncY/FRMbGJQpQyaGVOb2hFnHuxpLYMlXe+bLMZT0DO7EbY0+hdHdYMso3MNVi1Purgj46M0SAZt
Y9i08Ts/Qj4Ksq65uAXfKNa/nUWzIlOosn9KgmgR36NR6h8ljm3WczJUVWqRr4z4Y+szBUWLlBVa
3Sk3N8kOOR96o9YpRzVpBOcwyTrp+JFPaPRt/vKN6FPeYoMUZbm8U5Hh8lpyUzbznVupTg0Ak3Jq
0UWeneXQve7KNVKCi/R0Df+iDG0UM6rIR4kFYIop43iq1VTiHOuOC3lkrKx2iWOWTEWIoZUtckAQ
n7wQutBe6Dv7N9mADydMZWJW294+jd/Bhs2dteDJq9fXF1PBDhz/uTkqvggVHwPiwzfSAkbP7lyi
V2rLWUPwLoobOCVLKyskRzdgQgqYkRIOejYakVc0QY40kupt6reRzTqQZnfhDk1afUWWTwQupFa1
zQ76sLl7dmmLAQb69w2ozO0csv1rVceC1eGaIFO9Zw9NhIKPM/tRFmEkyZV1VXKTT+GqjBIx8iwy
2MitNrAtnBoXyVMZv041cq5tNcDT2qUApRZjTnvI0ZqJU+qZRxuo0VqlO5oYr1ZcIWmUXoRxaWIA
bp2esCuLxB8GBRXVayOxiKtBM4P0pn5aQE6tzVXBPyF/NyWvl/5dlzVMJu45mqtmdt8ZsPZpflW6
2e2qAvB7ik0y2hapiMFRRlbvSQEKFL2ccr5/iFkOZpX1SYrSGRW6F4fzlvGhKPRQeVh4FNMs+2zP
VNjp4GwjSDNbz8I4j+pRXtvEvFAPUiySM9WFAEqfLKaHlsoUvZ7RKgOjmVqI/sng3tVMP/36g3Zf
KANtoZYUbviojoRP/CmhmgO8Wnwz4e1K3sLvkmR9Ol1RVGMnW3uSZBWzzFqZhUs+oi9in41Vyzzg
abGGE3HIefquyRe4zk7p+AYmS79osqz6OTaqwiWEDMmKQw6IlEWU9Jfu1giDGFoI46W8E3KXL4l5
H6+8ylIbshix+3hjLK1aZuUgLXbsPs1S6xGMwQ0pWtBBqZMnnmR1KezYDZQ0m/ApbpXqGMSr6r3A
vbOPvI1MG+nzac4vucqVla9dzw6Z+x0NYU3F8SdBS+IkDyw0+035xw7gecTe0gH3CGlzHuywHmni
JLEypKf/5H1sb986bjo+nQqTwRcipR8a5AkyWpPWG4Vkt26ySQsLUCa0ym5IQMmCQAhtVHZynwwX
PjTfTLEnt+YgZmp8K50ZpRJOzfRa72qUxGivLddKp0N67dB5YLOndK+NXuQffrSMKzVYxyR73rJT
Ox1Gtsv4RXG0DamWYwvR4K8uEaXi1A6LapgRpp+BCblaIS+wJ0DlAR25afoN0c391Bh8CJy+D5/A
R9QzKFzcSQr7pkF5E5TH3h5Nhf3gIUiWav+p+JE+HcS6Nh8G/MRZUWyMU9QPTcnFlEejK0Eco1SC
8jyTg9+IA5uOdTDhsFMSUpkRdHpl9PCJeFR0MwvuA1VULYsADCldivhxjMRxcvITb3FuT/ApWfOx
Bc8tC1jOtrCOQ6ew7g/UaAr7hlJz1FCVGILOf0MVZFx9cAW8yFN203TWK7gs0ZyNAOg8WoEZoSH3
dVKwap9KNiIy+qsIW39Hi3jj5yiTTZNUFWMOA3RK/SgU1sfEB8aQW7ADL3Lb+r0C57JFPWsOFYob
HE7Y77umYMQ4NdKchhLtIZIbH2pn88aaIvKujIDhAl34kNcZcavcbSouX5xdTwdfT9rjk7t+e3g3
bA++7n/tIb0zDveALpZdco6nxz2xgmlq0xqND/kWx7fXMtU9jv2xqrrLVKT5wnL6W+scsbX2sxny
/7Vm4jZG9S+Bn6kh/8Rn4njqln5oY37zU0xZuLCBda2DLg0iT6b1Lvsz47Kdp0GtufQDfpBVdWT1
X/asvHojrA+t4aDMyx40ftaNG+JwYW43atNRkmyTrNZxNXvRIB61Q536TBIh9e2TWNN77Kptz4TM
o1b+sdUbtbTnGXVQ6zCuI67Ziek6blswm3/CZL/EmB7ZDYjrwqEL2nFv1Jvg8+lzaNBETQbLk6OT
3qI/OjmW/QWwmMij4cQdDuXxsO/2vMHyaDwWTwF7tmZxFL9cyuIbFSE81lmOZPYmVUuWtHknsJV8
F8h36G/O6SHcr35iXsWZ23XG0y9hfPjwP8o/tw0=
===END CRASH DUMP===

**Comment by DarkWav** [comment]
try to update again.

**Comment by GladiatorMine-Owner** [comment]
Add this packet for new 15.0 http://mark8.store.aptoide.com/app/market/com.mojang.minecraftpe/870150050/19339218/Minecraft+PE here apk,cant direct link bc on crappy hotel wifi srry,hope the link helps

**Comment by remotevase** [comment]
@GladiatorMine-Owner that does not help, because that does not show a single thing about packets. What will the apk do? Seriously, dude

**Comment by GladiatorMine-Owner** [comment]
decompile it and get the packet

**Comment by GladiatorMine-Owner** [comment]
....

**Comment by remotevase** [comment]
Can you do that for me? Honestly i dont know how to get the packets after you decompile it. If you are really as experienced as you claim, you will know how to do that

**Comment by GladiatorMine-Owner** [comment]
kk ill give link to unziped and ill ask my dev team if they can do it ,I should have it done very soon,a couple of days,srry if it takes a while

**Comment by remotevase** [comment]
thank you

**Comment by alicheek** [comment]
@DarkWav This is with the latest SRC folder

**Comment by Taki21** [comment]
The Protocol is 81 FOR SURE!!! Delete all other 2000 lel

**Comment by Taki21** [comment]
Proof: See the p81 on top?
![image](https://cloud.githubusercontent.com/assets/14851895/16165679/4a57e9cc-34b3-11e6-9d0f-de209d18ac15.png)

81 = Protocol

**Comment by lolcraftboy** [comment]
@remotevase when is it done

**Comment by remotevase** [comment]
@lolcraftboy sorry, i have little knowledge of how to fix this issue, so I'm just waiting for
a. PocketMine to fix
b. One of my teammates to fix it

**Comment by Ad5001** [comment]
Lol for myself I quite did not understand what this 'red laser' does. I might fix it if I understand what it is.

**Comment by remotevase** [comment]
Try joining my server and you will see it!
IP: the.servequake.com
Port: 19133

**Comment by Ad5001** [comment]
Wow just saw this... Strange...

**Comment by daniktheboss** [comment]
Hmm.. I don't have that when I start mine

**Comment by Taki21** [comment]
because u need another Player or Entity !!!

**Comment by Taki21** [comment]
For Example: Me and @remotevase are next to each other, u will see a red laser

**Comment by Taki21** [comment]
Grammer Correction: @remotevase and I ... Lel I am a professor xD

**Comment by remotevase** [comment]
XD lol. I tried to make a plugin that removes all other entities on load, but it didn't work

**Comment by HimbeersaftLP** [comment]
> XD lol. I tried to make a plugin that removes all other entities on load, but it didn't work

GrabBag -> /entities nuke all

**Comment by remotevase** [comment]
@HimbeersaftLP K thanks!

**Comment by Taki21** [comment]
lel

**Comment by remotevase** [comment]
Fixed in latest commit
