### ISSUE TITLE
y cant join my server

### ISSUE THREAD

**Issue by lolcraftboy** [Inactive-to-Reactive/ImagicalMine#27]
> ## **DO NOT DELETE THE FOLLOWING**

> ### Please Provide the Issue:

> - Edit This Text To Write Your Issue!

> ### Sources:

> - ERROR: Edit This Text To Write Your Issue!

> ### Please provide all that apply to this Issue!
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is written in your native language for maximal clarity
- [x] This issue does not have abbreveations. Abbreviations make it not understandable.
- [x] This issue is for ImagicalMine, and not any other server software
- [x] This is not a suggestion, but an actual issue

> ### Crashdump:

> - Edit This Text To Insert Your Crashdump

> ### Other INFO:

> - Edit This Text To Write Your Issue!

**Comment by lolcraftboy** [comment]
my game crast on loading screen

**Comment by lolcraftboy** [comment]
en how can y fix it

**Comment by Ad5001** [comment]
We don't know and this is an unknown issue that we don't know if we could resolve it yet.

**Comment by Taki21** [comment]
> Edit This Text 

May u please do that? Edit it and put your Issue,...

**Comment by remotevase** [comment]
Fixed in latest commit
