### ISSUE TITLE
ImagicalMine doesn't work since the MCPE upgrade to 0.15.0

### ISSUE THREAD

**Issue by donfrank43** [Inactive-to-Reactive/ImagicalMine#28]
> ## **DO NOT DELETE THE FOLLOWING**

> Issue:  ImagicalMine doesn't work since the MCPE upgrade to 0.15.0

> - Hi there,

  The Minecraft Pocket Edition 0.15.0, Android and Apple versions,  doesn't work anymore with the
  ImagicalMine Minecraft PE server version v0.14.x alpha.  Is there a slight chance of a solution?
  This would be appreciated. Thanks in Advance.

> ### Sources:

> - ERROR: Edit This Text To Write Your Issue!

> ### Please provide all that apply to this Issue!
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is written in your native language for maximal clarity
- [ ] This issue does not have abbreveations. Abbreviations make it not understandable.
- [ ] This issue is for ImagicalMine, and not any other server software
- [ ] This is not a suggestion, but an actual issue

> ### Crashdump:

> - Edit This Text To Insert Your Crashdump

> ### Other INFO:

> - Edit This Text To Write Your Issue!

**Comment by remotevase** [comment]
No chance. Reason: Too many packet changes. Therefore, use the current 0.15 src folder. Make sure that your server has no entities
