### ISSUE TITLE
Client times out on login

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/ImagicalMine#30]
login timeout again. Just needs to be re commited. Then we are done! I fixed the laser error! Now, we just need to fix the login timeout error and we are ready

**Comment by dterweij** [comment]
This belongs to this issue :)

```
[06:39:51] system> Starting GS4 status listener
[06:39:51] system> Setting query port to 19132
[06:39:51] system> Query running on 0.0.0.0:19132
[06:39:51] system> Default game type: Survival Mode
[06:39:51] system> Done (1.156s)! For help, type "help" or "?"
[06:40:49] system> [/192.168.0.204:19132] logged out due to Login timeout
[06:42:03] system> [/192.168.0.204:19132] logged out due to Login timeout
[06:42:06] system> [/192.168.0.231:19132] logged out due to Login timeout
[06:42:44] system> [/192.168.0.231:19132] logged out due to Login timeout

```

**Comment by Ad5001** [comment]
Cool !

**Comment by lolcraftboy** [comment]
Stille cantate join nu server ):

**Comment by Ad5001** [comment]
We know. But it's moving forward to it !

**Comment by Mike4l6** [comment]
the src folder is still 14.x

**Comment by remotevase** [comment]
what? No it's not?!

**Comment by Mike4l6** [comment]
try the phars are 0.15 but the src is 0.14.x

**Comment by Ad5001** [comment]
So your change make it go backwards? Genisys , ClearSky and pocketmine are also crashing on connection and apparently, it's client fault.

**Comment by remotevase** [comment]
They have different issues than us! For them, it is due to a new map loading problem. For us it is due to this

**Comment by Ad5001** [comment]
But this was fixed before your changes !

**Comment by remotevase** [comment]
what? No...

**Comment by lolcraftboy** [comment]
When is this fixt a hate genisys end clearsky

**Comment by lolcraftboy** [comment]
Sorry if translate is rong

**Comment by lolcraftboy** [comment]
Y hoop soon 😊😎😉

**Comment by Mike4l6** [comment]
I also have this issue lol

**Comment by Ad5001** [comment]
@remotevase When the client crashed, it wasn't any login timeout !

**Comment by remotevase** [comment]
yes, but client crash was due to the laser. Fixing the laser brought this.

**Comment by remotevase** [comment]
I have been trying to fix so many times, hasn't even worked once :(
Should hopefully be fixed by Tuesday

**Comment by Mike4l6** [comment]
Hopefully..

**Comment by remotevase** [comment]
I did lots and lots of code cleanup, and I hoped that the cleanup would fix this; apparently not...

**Comment by Ad5001** [comment]
I saw when you tried to fix the red laser (the first time) you modified the LoginPacket and the Info.php . It might come from those commits since you said in your "new red laser fix" commit that the other did not work...

**Comment by remotevase** [comment]
the laser is fixed, as after a few attempts, I was able to connect with no errors

**Comment by Ad5001** [comment]
Like CONNECTING ? Without LOGIN TIMEOUT? OMG !

**Comment by Driesboy** [comment]
work?

**Comment by remotevase** [comment]
If you try it a few times, you are able to connect (like a few, i mean 30-40)

**Comment by Mike4l6** [comment]
Well.. 
[16:23:38] system> Mike4l6[/192.168.1.8:19132] logged out due to Login timeout

**Comment by remotevase** [comment]
yeah how many times did you try?

**Comment by Mike4l6** [comment]
2-5 this is still a bug, you should be able to go on the server in a few tries

**Comment by Mike4l6** [comment]
Warning: Illegal offset type in isset or empty in phar://C:/Users//Documents/PocketMine-MP/Pocketmine-MP.phar/src/pocketmine/entity/Entity.php on line 466

Warning: Illegal offset type in isset or empty in phar://C:/Users//Documents/PocketMine-MP/Pocketmine-MP.phar/src/pocketmine/entity/Entity.php on line 466
[10:21:30] system> MainJungle80662[/192.168.1.7:19132] logged out due to Login timeout

**Comment by Ad5001** [comment]
Do you have any plugin related to effects on join ?

**Comment by Mike4l6** [comment]
Sorry for putting that here instead of putting a new issue but,
here

ImagicalMine 1.5: 1vs1 0.0.5; AdminFun 1.0.0; Alias 1.2.0; AlwaysSpawn 2.2.2; AntiCheat 1.12.3; AntiForceOP 1.0.0; AntiSpam 1.3; BlockBoost 1.0.0; BlockSniffer 1.0.0; ClearLagg 1.1.0; CraftingTableFix 2.0-Alpha; CTF_DODO 1.1.0; CustomJoin 1.0.0; DamageIndicator 1.0.0; DisableHungerPerWorld 1.0_Dev; EAC 1.2.1; EasyCMD 1; EconomyAPI 2.0.9; EconomyAuction 2.0.2; EconomyCasino 2.0.2; EconomyJob 2.0.4; EconomyLand 2.0.9; EconomyProperty 2.0.6; EconomyPShop 2.0.2; EconomySell 2.0.7; EconomyShop 2.0.7; EconomyUsury 1.0.1; EffectsCommands 1.6; Elytra 1; EssentialsPE 2.0.0; FactionsPro 1.3.2; FileManager 1; Functions 1.0; HealthTag 1.0.0; HereAuth 1.0-Beta#174; HomeTeleporter 3.2; ImagicalPlugInstaller 1.2; InventoryExchanger 2.3.0; iProtector 3.1b; ItemCloud 1.3; Levitation 1.0; Lightning_Strike 2; ManyWorlds 2.0.3; MineReset 2.1; NoAdvertisingPE 1.0.1; NoOpCMD_Prank 1.0.0; Parkour 1.0.0; ParticlesPlus 0.0.2; Plugswork 9.php.bleed; PmChair 1.2; PurePerms 1.3.7-patch1; RestartMe 1.2.0; ServerHub 1.0.0; SexyMOTD 1.0.0; SurvivalGamesV3 3.1.2; SignShop 2.0.0build3; SignTP 1; SkyWarsDoDo 1.0.0_Reloaded_ENGLISH; Slapper 1.2.9.3_PHP7; SpecialBlock 1.3.4; SpeedRun 1.0.0; StatsMe 1.0.0; SteakIt 3.0.0; superBAR 1.4.10; SwaggyNames 1.0.0; TapToDo 2.2.1; Texter 2.0.0; TimeCommander 2.1; TimerBan 2.1; VoteReward 3.0.2; WordBlocker 1.0.0; WorldEdit 3.2; WorldGM 1.1.0; xyz 1.0.1; EconomyAirport 2.0.4; PureChat 1.4.0

**Comment by Ad5001** [comment]
Try to remove / reset SpecialBlock... it can come from some of their commands...

**Comment by Mike4l6** [comment]
ok,
 I hope the login timeout bug will be gone

**Comment by HimbeersaftLP** [comment]
Hey guys, just discovered, that pocketmine also has the red laser bug, but their laser is brown!

[Imgur](http://i.imgur.com/AOmJTo9.jpg)

**Comment by remotevase** [comment]
Thats a leash, silly! Our former red laser caused the client to crash as a form of debug! Pocketmine apparently figured out how to change the item that connected the player to the entity, but not how to remove the connector! They changed it to a leash so that the client does not crash! Smart!

**Comment by remotevase** [comment]
Im gonna look in pocketmine's commits to try to figure out how they did this

**Comment by Driesboy** [comment]
look on genisys
its up todater than pocketmine

**Comment by remotevase** [comment]
Ah ha! See https://github.com/PocketMine/PocketMine-MP/commit/df8e1e87024f3f70ee91d15d936fe48dbda08ec9

**Comment by remotevase** [comment]
Scratch that, I think we should try this instead
https://github.com/iTXTech/Genisys/pull/1185/files

**Comment by remotevase** [comment]
So, thanks to @HimbeersaftLP I will be doing some more local testing over today and tomorrow, and will likely figure it out!!!!!

**Comment by Ad5001** [comment]
Oh cool !

**Comment by Ad5001** [comment]
Actually, you should also look at ClearSky that implemented tons of new things of 0.15 and that's working

**Comment by Driesboy** [comment]
but i think we need to add synapse

**Comment by HimbeersaftLP** [comment]
> So, thanks to @HimbeersaftLP I will be doing some more local testing over today and tomorrow, and will likely figure it out!!!!!

xD, I just found that randomly when testing StatsMe together with my brother xD

**Comment by Ad5001** [comment]
StatsMe power.

**Comment by HimbeersaftLP** [comment]
> StatsMe power.

BoxOfPower

**Comment by remotevase** [comment]
Fixed! Now it crashes, idk why, someone try to fix

**Comment by Mike4l6** [comment]
It crashes when your trying to connect or is that a Ios bug?

**Comment by Driesboy** [comment]
@remotevase do you have downloaded map?

**Comment by Ad5001** [comment]
After connection, I get this error: Call to undefined method pocketmine\item\ItemBlock::getProtection()" (EXCEPTION) in "/src/pocketmine/inventory/PlayerInventory" at line 735

So this can be a problem related to player inventory

**Comment by Ad5001** [comment]
And this one too:  Error: "Call to undefined method pocketmine\level\Level::getUsingChunk()" (EXCEPTION) in "/src/pocketmine/level/Level" at line 999

**Comment by remotevase** [comment]
hmm... I didn't get either of those, @ad5001...

**Comment by Ad5001** [comment]
Nevermind, they don't show anymore...
Errors releated to the player that does not really connect.

**Comment by Mike4l6** [comment]
does the slapper plugin have to do with anything,
no its not a downloaded map

**Comment by Mike4l6** [comment]
It crashes now

**Comment by remotevase** [comment]
Yeah, I know, but I don't work on this anymore, that's for @Ad5001

**Comment by TheProest35YT** [comment]
Is it fixed or not

**Comment by Sandertv** [comment]
Well this is, but now the player crashes on join...

**Comment by TheProest35YT** [comment]
Is the protocol changed to the correct protocol ?

**Comment by Sandertv** [comment]
The protocol is correct yes.

**Comment by TheProest35YT** [comment]
OK
I will try using IM

**Comment by TheProest35YT** [comment]
Can't believe my MCPE crashed using IM

**Comment by Sandertv** [comment]
Could you screenshot most of the console on startup for me? Idk if we can see anything in it but I can try.

**Comment by TheProest35YT** [comment]
![screenshot_2016-08-22-14-51-58_net pocketmine server](https://cloud.githubusercontent.com/assets/19955608/17845941/25359de4-6878-11e6-82ae-1ad27048351e.png)

**Comment by Sandertv** [comment]
Did you stop the server yourself?

**Comment by Ad5001** [comment]
The warning o.O This meas android has liux in It's name !

**Comment by TheProest35YT** [comment]
@Sandertv no

**Comment by TheProest35YT** [comment]
I will try the Genista App to try IM too

**Comment by Sandertv** [comment]
So the server stopped when you joined the game?

**Comment by TheProest35YT** [comment]
Yed

**Comment by TheProest35YT** [comment]
Yes

**Comment by Sandertv** [comment]
Hmmm...

**Comment by TheProest35YT** [comment]
Maybe PocketMine App has a problem

**Comment by TheProest35YT** [comment]
Or ImagicalMine 1.5 works on Windows PC :o

**Comment by remotevase** [comment]
@Sandertv what he did": He edited the PM app so that it would run IM. That usually causes problems like this. It has caused problems like this since IM first came out, and since someone edited the PM app to make it IM.

**Comment by remotevase** [comment]
Therefore the "Stopped the server when player join" cannot be considered a revelant issue. It has been an issue that has been around for the past (almost) year

**Comment by Sandertv** [comment]
Okie

**Comment by remotevase** [comment]
0.15.0 and 0.16.0 because even though there are 0.16 errors, on the device, it says "Login Timeout"

**Comment by Mike4l6** [comment]
:/ this bug is annoying

**Comment by remotevase** [comment]
ikr

**Comment by TheRoyalBlock** [comment]
Project dead. Click the link in the readme for a new branch. The link is being updated whenever possible so it always remains active some way or another.
