### ISSUE TITLE
Make Something New?

### ISSUE THREAD

**Issue by ImagicalGamer** [Inactive-to-Reactive/ImagicalMine#31]
ImagicalMine is scarcely used and is mostly a fork of PocketMine-MP. Personally I think we need to make something 100% new from scratch. Reply with your thoughts

**Comment by remotevase** [comment]
Actually, it is quite commonly used! I learned that on some of Kingdoms Craft's more minor servers, they run ImagicalMine!!! Not scarcely!
Few problems with new from scratch:

1. We will have to rewrite all of the plugins
2. We will still end up following the basis that pocketmine used with the "src\imagicalmine\..." and all that
3. It will likely take a really really long time to figure it all out
4. It must be written in php as that is the most commonly known language between the team members, but that means that there will be lots of updates required, and lots of syntax errors which we all hate

Good things:

1. We understand it better
2. Therefore, we can implement more features like plugins have them
3. We will have our very own thing to be proud of and wont have to worry about other licenses
4. Code will be automatically cleaned up because thats what we do in rewrites! (And code cleanup was something major on the to do list)

**Comment by ImagicalGamer** [comment]
I never said PHP did I? PHP is slow asf.

**Comment by Ad5001** [comment]
Erm... almost all of us are not understanding other languages (I think you talk about js but js is as slow as php :/)

**Comment by TheKnightGamer** [comment]
Yeah we can make ImagicalMine from scratch. Let chose a language C++ , PhP or Java.

**Comment by AutiAuto** [comment]
Better don't use Java. The whole idea of Minecraft PE and Windows 10 Edition was to avoid using Java, because it's slowly dying of.

**Comment by Taki21** [comment]
What ya mean @AutiAuto ?

**Comment by Taki21** [comment]
Guys i recently went to the PHP Hospital to check my allergy on elseif {} ... Its doing ok :)

**Comment by Sandertv** [comment]
@Taki21 don't think It's over yet, the elseif{} sickness has 2 stages, you just finished the first, but now You're going to be allergic to else{}

**Comment by Taki21** [comment]
NOOOO!!!!!

**Comment by Taki21** [comment]
I NEED A BETTER DOCTER!!!!

**Comment by Taki21** [comment]
Guys!! I'll create a different REPO!!! AND WE DO WEWITE YAY!

**Comment by Sandertv** [comment]
Wait wat? You can't rewrite imagicalmine without else{}!!!

**Comment by Taki21** [comment]
Oh lol! Went to a doctor 2 meters away and got a nice treatment :P

**Comment by Taki21** [comment]
https://github.com/Inactive-to-Reactive/ImagicalSoft

**Comment by Taki21** [comment]
Lets get started

**Comment by HimbeersaftLP** [comment]
@Taki21 Just did some emoji spam on your posts :P

**Comment by Sandertv** [comment]
And mine @HimbeersaftLP 😨

**Comment by HimbeersaftLP** [comment]
@Sandertv I also liked yours :P

**Comment by Taki21** [comment]
lel

**Comment by Sandertv** [comment]
The blushing smileys are so creepy... their laugh is so adorable it's creepy as hell...

**Comment by TheKnightGamer** [comment]
Why did you call it ImagicalSoft

**Comment by remotevase** [comment]
It will not be imagicalsoft, it will be called ImagicalMine! The  branch will be ImagicalMine-Remake, and I will start it. The way taki did it is not how i expected

**Comment by TheKnightGamer** [comment]
I can help you remake ImagicalMine

**Comment by TheKnightGamer** [comment]
Wait what language we are using?

**Comment by remotevase** [comment]
php! Before you help, wait to see the setup that I am using. I am coming up with a format for it

**Comment by remotevase** [comment]
It should be done in a about 20 mins

**Comment by TheKnightGamer** [comment]
Ok  I just made the main chat over there.

**Comment by Mike4l6** [comment]
1 hour later..

**Comment by Taki21** [comment]
Call it something different

**Comment by Taki21** [comment]
# **Ur remaking it**

**Comment by Taki21** [comment]
## Its like saying:
> Im a blue duck 
> then
> u paint it white ("remake it")
> U still call it Blue Duck

**Comment by Taki21** [comment]
I vote for ImagicalSoft

**Comment by Taki21** [comment]
Think of a new name with Imagical beside Mine.

**Comment by Sandertv** [comment]
I liked Imagicalmine...

**Comment by legoboy0215** [comment]
This conversation is giving me cancer...

**Comment by legoboy0215** [comment]
Don't get me wrong, but I think it is very hard to keep up with the quality of Genisys.

**Comment by ImagicalGamer** [comment]
What the %$@# I just read the format were using and we would have to edit ALL plugs to make them work with the new ImagicalMine.

**Comment by starterdragon** [comment]
Is it possible to use Go Lang? just asking.

**Comment by Ad5001** [comment]
Go Lang?

**Comment by starterdragon** [comment]
I heard Google's Go programming language is fast, and I'm trying to study it. maybe server's will perform better than php based server softwares, but Idk if it is faster than C++ though.

**Comment by legoboy0215** [comment]
There is already a server software in Go.

**Comment by xBeastMode** [comment]
Can it be in Fortran?

**Comment by keithkfng** [comment]
@legoboy0215 no no no, there **was** a server software **programmed** in Go. It's inactive now and the project is dead.

**Comment by keithkfng** [comment]
Anyway, if you're going to make something new, make up a new name. ImagicalMine is reserved for the forums already :P

**Comment by starterdragon** [comment]
It's almost similar to Java and/or PHP so maybe rewritting the main file or plugins aren't that hard rather than using C++

**Comment by Taki21** [comment]
true but...some "stuff" will be different.

**Comment by Sandertv** [comment]
WATCH OUT THERE'S AN ELSE{} ATTACKING TAKI

**Comment by remotevase** [comment]
@Sandertv see the new label

**Comment by Sandertv** [comment]
Yay! It's perfect!

**Comment by daniktheboss** [comment]
Python. No one said python. 1. Fast 2. Easy 3. Simple 4. Cool 5. Why not 6. Better then php 7. Mostly done already

**Comment by ImagicalGamer** [comment]
@daniktheboss Anything is better than PHP

**Comment by Taki21** [comment]
lol @ImagicalGamer

**Comment by remotevase** [comment]
@Daniktheboss as we mentioned above, the majority of people here only use php

**Comment by keithkfng** [comment]
Then maybe learn a different language...

**Comment by daniktheboss** [comment]
Wow. So you learn one thing and stop? What kind of coding is this? Just
forking a project that has a million of holes with so much forks and keep
on working with it? The devs at pocketmine stopped! It's time to move on to
different languages and stop being kids!

**Comment by jasonwynn10** [comment]
damn thats harsh

**Comment by legoboy0215** [comment]
lol

**Comment by jasonwynn10** [comment]
there are already versions of pocketmine in other languages like java, js, and c++... If we were to do something like that, we should make it look and act as close to bukkit servers with a new language not already used.

**Comment by remotevase** [comment]
Unfortunately, it will take a few more years until I stop being a kid... Sorry, @daniktheboss. If you meet me in real life, you would know: being and acting like a kid is kind of what I do all day...

**Comment by remotevase** [comment]
@jasonwynn10 precisely. I have plans to learn jquery and Python soon, but I doubt either of these could be used for mcpe

**Comment by Taki21** [comment]
If u know 1 language... it will be less challenging to learn another :p

**Comment by remotevase** [comment]
i guess so...

**Comment by legoboy0215** [comment]
Node.js is a chance too.

**Comment by jasonwynn10** [comment]
we should make a server with a built in interface for the people who want it

**Comment by Taki21** [comment]
guys u do know that addons and commands like /op are in 0.16.0 right?

**Comment by Taki21** [comment]
Does that pop an idea to any of u?

**Comment by Taki21** [comment]
(Addons as in like... plugins except ingame)

**Comment by Taki21** [comment]
But @daniktheboss (da boss) is right,... xD

**Comment by remotevase** [comment]
@taki21 idk what you are hinting at, but all I know is that it will be super hard to implant

**Comment by remotevase** [comment]
Implement not implant lol

**Comment by legoboy0215** [comment]
Addons won't do anything. It is just some JSON editing.

**Comment by jasonwynn10** [comment]
does anyone know if there will be the any ability to ensure that players will be connected to xbox in the new version? if so, we could make it an implementation as a built in login system

**Comment by legoboy0215** [comment]
Yes. See a project called [Genisys](https://github.com/iTXTech/Genisys)

**Comment by Taki21** [comment]
Json makes aliens?

**Comment by remotevase** [comment]
@legoboy0215 see clearsky as well. Genysis sucks...
@Taki21 json and txt files. Aliens like that will be easy to create, read [this](http://news.xbox.com/2016/09/24/boss-update-add-ons-coming-minecraft-october-18/)

**Comment by Sandertv** [comment]
Guys. I think we should let go of ImagicalMine and try to contribute to this instead...
http://forums.pocketmine.net/threads/phoenix-the-future-of-pocketmine.18386/
If you don't agree, sure, but I feel like this is the best option.

**Comment by ImagicalGamer** [comment]
@Sandertv I agree fully, ImagicalMine has lived longer than anyone though. It's barely alive now, not much new is being added. We need to move on to something better.

**Comment by jasonwynn10** [comment]
and with that, the PM community was officially destroyed...

**Comment by remotevase** [comment]
Sounds nice...

**Comment by Taki21** [comment]
Hah... im just laughing at that... Watch as that falls too and if you don't believe me you just made me laugh even more!

**Comment by Taki21** [comment]
> It also disgusted me how little originality there is. Genisys is the leading spoon currently, with some devs who actually do know how to do things other than copy-paste... but there is not much originality to Genisys (Lots of the "features" Genisys has are copied from poorly-written plugins), and even less so to other spoons. ImagicalMine and ClearSky were and are respectively prime examples of this - they copied/copy most of our developments. (Not to be hypocritical, Genisys devs have copied from other sources before - most notably PocketMine! >:-{)

i cant stop laughing at this hah....

**Comment by Taki21** [comment]
No matter what... it will be dead... every server software will be dead. Why? Compare PC Software TO PE and see how embarrassing it is. PM died and 3rd Party groups will just fail as well eventually

BUT

If you are that person who DOESNT EVER GIVE UP Dont let this thing die like this! Feel free to copy paste! Feel free to test! Feel Free to do your own codes in this project! We are all the same server software group! We should all share codes like a coding community! After all, aren't we all in the same group of community? When people realize this... that's when these groups won't die... they might even start to work on 1 thing together and stick to that and work on that! @remotevase Don't make your time to waste! Don't give up! Time is valuable! You worked on this for a reason!

**Comment by Taki21** [comment]
And if starting a new path is the right path take it! Don't change your route! We don't need 100 duplicates! @remotevase and my fellow Swag Gansters xD Lets stop talking and do action! Why _**Why Dont we START Something new?! Actions value more than words!**_

**Comment by Taki21** [comment]
With code ... anything can happen! The Possibilities are Infinite! Yay Thanks guys for wasting ur time jk xD

**Comment by remotevase** [comment]
Honestly, your words seemed to be a total mess to me, but I agree that currently Phoenix sucks and hasn't even started work on 0.16...  Maybe in the future it will be good, but now it not good... I still hope for DevMine to be good if somebody could just figure out the issue...

**Comment by Taki21** [comment]
> Yay Thanks guys for wasting ur time jk xD

**Comment by jasonwynn10** [comment]
Here's some irony: the organization is inactive to reactive, but most of the repos here aren't active at all. only this one

**Comment by remotevase** [comment]
and the new repo that i am creating

**Comment by jasonwynn10** [comment]
here's an idea! make a server that isn't based on PocketMine or the forks that can implement the Plugin API for MCPE 0.16 ?https://youtu.be/e2MNYIa411k?t=21m18s

**Comment by Taki21** [comment]
guys thats what i was saying the whole time about JSON!!!!

**Comment by Taki21** [comment]
ALso, at mojang minecon, it says you need to download add in before playing this realm!!! This is good! If only we can do that but with servers for free with unlimited players!

**Comment by Taki21** [comment]
guys lets pm before someone steals this idea ill delete all comments asap ok?

**Comment by Taki21** [comment]
please see my pm on im forums :)

**Comment by Sandertv** [comment]
Damnit I've got none...

**Comment by TheRoyalBlock** [comment]
Project dead. Click the link in the readme for a new branch. The link is being updated whenever possible so it always remains active some way or another.
