### ISSUE TITLE
Rename tile -> blockentity

### ISSUE THREAD

**Issue by mixailenko5** [Inactive-to-Reactive/ImagicalMine#32]
Rename tiles to blockentity as https://github.com/iTXTech/Genisys/commit/a2f4995ce17c859d617baa7b8ba664202244b3e0 please.
For my opinion it's important fo plugin developers, because they like support of their plugins on all popular nucleis.

**Comment by Driesboy** [comment]
it dont work check this https://github.com/iTXTech/Genisys/issues/1295
