### ISSUE TITLE
Control app?

### ISSUE THREAD

**Issue by daniktheboss** [Inactive-to-Reactive/ImagicalMine#34]
Hello, sorry if I am spamming but I don't know where else to put this in... leet has a very nice handy app! That u can control the whole server with! How did they do that??? Is there a app already made or somthing for that, that people can download? But thanks! And sorry again lol

**Comment by Sandertv** [comment]
Leet is a server host, while imagicalmine is just the software a host could use, it's basically two different things :P There is though, a pocketmine-mp app on play store you can use, but it's a bit harder than leet to setup but it's free. (You will need a good computer to make a decent server with that though)

**Comment by daniktheboss** [comment]
Yea I know but downloading the pocketmine app u will host the server on phone right?

**Comment by Sandertv** [comment]
Yup

**Comment by Sandertv** [comment]
That was just a possibility :tongu

**Comment by Sandertv** [comment]
But no, currently we don't have one of these since Imagicalmine doesn't provide hosting!

**Comment by Ad5001** [comment]
You mean an app to control your server? I was starting doing one on Windows but don't exept seeing one on phone (like apple ask $99 just to publish one app and you need to reay every year) and I dont think we would do this until we know C++ / C# and having a large amount of donations.

**Comment by remotevase** [comment]
you can use plugswork

**Comment by remotevase** [comment]
it's a plugin

**Comment by Ad5001** [comment]
He mean an app not a website (but we could create an app from a website !)

**Comment by HimbeersaftLP** [comment]
> He mean an app not a website (but we could create an app from a website !)

Yeah, windows phone allows you to create plugins with html

**Comment by Ad5001** [comment]
No way serusly?

**Comment by Ad5001** [comment]
(Like windows with HTAs)

**Comment by daniktheboss** [comment]
Ok thanks I might just use the Web. Hope someone makes an app like that. I've read that the leet devs said they used xcode.

**Comment by Ad5001** [comment]
We already know. It's the only code editor for Apple devices. And they actually pay $99 per year for their app ! (due to the money they are making, it's almost nothing, but if any of do this, no one will use it if he needs to pay or having ads :/)

**Comment by daniktheboss** [comment]
Or he can make a apk and ipa or whatever for ios.... and people can download the apk...

**Comment by daniktheboss** [comment]
And the plugswork site is down..

**Comment by Ad5001** [comment]
Android (if we know how to code C++) wouldn't be that hard. iOS is an other thing. If we don't have an "Apple certification" no one can download our apps :/

**Comment by daniktheboss** [comment]
Ohh, well then we will have to wait and hope for the best

**Comment by remotevase** [comment]
> if we know how to code C++

I don't know...

**Comment by daniktheboss** [comment]
Plugswork project is done... there not working on it anymore

**Comment by Taki21** [comment]
@Ad5001 Incorrect. U need Java to make an Android App lel :P C+ C# C poop >>> Computer Application Poop,,,Lel

**Comment by Taki21** [comment]
> Taki = Attacked by Else{}

._.

**Comment by Taki21** [comment]
Apple...I dont why we have to pay $99 every year for membership poop...ugh

**Comment by Taki21** [comment]
submitting an app on play store for like almost $30 is more reasonable

**Comment by Ad5001** [comment]
Yeah but there are already a lot of concurrents on PlayStore. And in case you did not know, most of the mobile apps are running C++ and a bit of java. Java is too slow for big apps (like MCPE which is coded in C++.

**Comment by Taki21** [comment]
nooo....When u decompile MCPE its ALLL java! :p

**Comment by Ad5001** [comment]
True, but if you know java, you should know that this is NOT the source code.

**Comment by Taki21** [comment]
it is... ._.

**Comment by Taki21** [comment]
com.poop.poop
has all that

**Comment by Taki21** [comment]
and all java btw

**Comment by Taki21** [comment]
Check android studio. Thats how everyone creates Android Apps.

**Comment by Appadeia** [comment]
"everyone" I do asm for my Samsung xD... Not really effective for wide-platform development, but wow it's fast and you have **every. single. level. of control.**

**Comment by remotevase** [comment]
why is this issue still open? Should be closed, but just because it is closed doesn't mean that we can't use it as a partial forums

**Comment by remotevase** [comment]
oops lol

**Comment by daniktheboss** [comment]
Lol
