### ISSUE TITLE
Broadcast of wrong mcpe version

### ISSUE THREAD

**Issue by Appadeia** [Inactive-to-Reactive/ImagicalMine#35]
> ## **DO NOT DELETE THE FOLLOWING**
> ### Please Provide the Issue: No clients can join.
> - The server broadcasts the version as **0.15.0.x** instead of **0.15.x**, causing all mcpe players to be kicked off.

**Comment by Mike4l6** [comment]
Maybe.. 
idk

**Comment by remotevase** [comment]
could this really be the reason?

**Comment by Mike4l6** [comment]
Its possible most people have 0.15.1, even the ios users who have still 0.15.0 can't join does 0.15.0.x mean beta builds?

**Comment by remotevase** [comment]
on Android it is 0.15.0.1 or 0.15.1.0

**Comment by remotevase** [comment]
so, I think it should be 0.15.x.x

**Comment by Taki21** [comment]
Weird i have an android and an iOS ... 1 has 0.15.0 and the other has 0.15.1 (Android NOT BETA)

**Comment by Taki21** [comment]
yes 0.15.0.xmeans beta

**Comment by Ad5001** [comment]
I tried change it but still crash

**Comment by Mike4l6** [comment]
Ios has 0.15.2 now lol

**Comment by ImagicalGamer** [comment]
xD

**Comment by Mike4l6** [comment]
I dont know if this helps but Genisys uses the broadcast version just 0.15.0

**Comment by remotevase** [comment]
Hm and does it work with 15.2?

**Comment by Mike4l6** [comment]
yep works on Ios and Win 10 which means also android

**Comment by remotevase** [comment]
Really? Hmmm @Ad5001 did you test this exactly, of not, try setting it to 15.0 not 0.15.2 or whatever you are using

**Comment by Ad5001** [comment]
When I will have the time...

**Comment by remotevase** [comment]
kk

**Comment by Mike4l6** [comment]
take out the 0.15.0**.0** the extra 0

**Comment by Dog2puppy** [comment]
Never happens for me.

**Comment by jasonwynn10** [comment]
needs to be 0.15.6 now

**Comment by Sandertv** [comment]
Yeah true, though that shouldn't really matter... It really doesn't make a difference.

**Comment by TheRoyalBlock** [comment]
Project dead. Click the link in the readme for a new branch. The link is being updated whenever possible so it always remains active some way or another.
