### ISSUE TITLE
gamecraftpe.tk : test server?

### ISSUE THREAD

**Issue by Driesboy** [Inactive-to-Reactive/ImagicalMine#4]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

ip: gamecraftpe.tk
port: 19132
ps: now on genisys but i will change

**Comment by AmiroEmad** [comment]
what does relate this to imagicalmine issue tracker

**Comment by Driesboy** [comment]
there is no chat room!
