### ISSUE TITLE
I believe that I fixed it...

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/ImagicalMine#40]
I just committed the commit
"Finish 0.15 update"

So, could somebody please test from 
[this branch?](https://github.com/Inactive-to-Reactive/ImagicalMine/tree/680e4358182144fc60abf0ea0701192e4c34f8d3)

I believe I have fixed the crashes!

Thanks!

**Comment by Ad5001** [comment]
Gonna test it.

**Comment by Sandertv** [comment]
Oh my god if this works I'd be so happy.

**Comment by Ad5001** [comment]
Crashes the client

**Comment by Sandertv** [comment]
Is that a ported map? Or a pocketmine generated one?

**Comment by Ad5001** [comment]
I used one of my clearsky maps.

**Comment by Sandertv** [comment]
Anything in console? Or just client timeout?

**Comment by Ad5001** [comment]
Nothing on the console. The server things the client connected and then timeout.

**Comment by Mike4l6** [comment]
timeout

**Comment by remotevase** [comment]
:(

**Comment by remotevase** [comment]
Well, at least we see something in console!

**Comment by Sandertv** [comment]
Man I wish I could help you...

**Comment by remotevase** [comment]
@Sandertv omg i JUST REALIZED!!! YOU WERE NOT INVITED!!!!!!!!! sorry blabla

**Comment by Sandertv** [comment]
:tongue

**Comment by Sandertv** [comment]
I don't understand... @remotevase did everything pocketmine did and it's not working... (yes I checked through everything)

**Comment by Ad5001** [comment]
Yeah but pocketmine isn't working too !

**Comment by Sandertv** [comment]
It isn't??

**Comment by Sandertv** [comment]
Oops sorry, missclicked, doesn't it?

**Comment by Ad5001** [comment]
Last time I tried it, no.

**Comment by remotevase** [comment]
@Sandertv I also did everything clearsky did, and its still not working. Clearsky **does** work, unlike PocketMine

**Comment by Ad5001** [comment]
That's somethig else...
Did you add all entity's leahable or not?

**Comment by remotevase** [comment]
What?

**Comment by Sandertv** [comment]
Leashable he ment, like pocketmine had, with those leashes...

**Comment by remotevase** [comment]
oh... No i dont think i did that...

**Comment by iPocket** [comment]
WTF is Taki=attacked by else{}??!

**Comment by Sandertv** [comment]
Maybe we should use the 'before-messing-up' branch and try to do the changes pocketmine has first to see if that works and move on if it does?

**Comment by Sandertv** [comment]
Oh nevermind I see you did try that already...

**Comment by remotevase** [comment]
just tried again, I believe it no longer crashes

**Comment by daniktheboss** [comment]
Joins?

**Comment by remotevase** [comment]
I didnt test, but I fixed some stuff, and I think that it doesnt crash on join. Can someone test?

**Comment by Ad5001** [comment]
Still crash @remotevase

**Comment by remotevase** [comment]
:(

**Comment by Taki21** [comment]
its me and @remotevase and @ImagicalGamer 's special "phrase" for me since i have an allergy to else...and else if() :)

**Comment by Sandertv** [comment]
@Taki21 *Achum*

**Comment by Taki21** [comment]
lol

**Comment by jasonwynn10** [comment]
seems un needed

**Comment by iPocket** [comment]
truth.

**Comment by Taki21** [comment]
Taki Attacked by Else If() = Invalid Issue  thats also part of this XD

**Comment by jasonwynn10** [comment]
whatever... -_-

**Comment by Taki21** [comment]
I need to let u know that i was attacked! this is serious dude!

**Comment by Taki21** [comment]
Just  saying the nest protocol is 90

**Comment by remotevase** [comment]
Damn it

**Comment by Ad5001** [comment]
I don't wanna be  discouraging,but if you heard, the protocol will be 100% rewrite ...

**Comment by iPocket** [comment]
That causes software rewrite

**Comment by Taki21** [comment]
Ya ... have the beta so much new things

**Comment by remotevase** [comment]
Ugh... I think then I will just fork pm or cs then add IM's features to it

**Comment by TheRoyalBlock** [comment]
Project dead. Click the link in the readme for a new branch. The link is being updated whenever possible so it always remains active some way or another.
