### ISSUE TITLE
FORUMS!!!!

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/ImagicalMine#45]
We officially have a forums! It is a complete work in progress. More plugins and extra features are coming to the forums very soon!

Visit the site at
http://IMForums.ml

**Comment by remotevase** [comment]
Currently, my account is ImagicalMine_Admin.
I will start a conversation with all staff members, then also start a conversation with all **super duper trusted** staff members. Then I will make my personal "remote_vase" account

**Comment by iPocket** [comment]
I visited it

**Comment by iPocket** [comment]
The website is buggy

**Comment by iPocket** [comment]
Trying to add a profile picture but page not found
And the website is so bad except the style :D
the profiles are empty

**Comment by iPocket** [comment]
Email verify doesn't work.

**Comment by dterweij** [comment]
Not reachable from The Netherlands.

```
traceroute to imforums.ml (195.20.54.53), 30 hops max, 60 byte packets
 1  router (192.168.0.1)  0.142 ms  0.137 ms  0.141 ms
 2  cabel-modem (10.202.32.1)  9.545 ms  11.079 ms  14.080 ms
 3  asn-rc0002-cr101-xe-0-2-0-0.core.as9143.net (213.51.184.216)  18.296 ms  18.320 ms  18.339 ms
 4  uk-lon01b-rd1-xe-1-1-0-0.aorta.net (84.116.134.53)  24.247 ms  24.342 ms  24.264 ms
 5  fr-par02b-rd1-xe-3-1-3-0.aorta.net (84.116.134.54)  27.443 ms  27.447 ms  27.612 ms
 6  213-46-161-146.aorta.net (213.46.161.146)  27.466 ms  26.974 ms  26.977 ms
 7  xe-9-0-2.ams12.ip4.gtt.net (89.149.180.137)  26.990 ms xe-11-2-3.ams12.ip4.gtt.net (89.149.128.17)  9.675 ms  15.687 ms
 8  pni-as3257-ams1.staminus.net (69.197.1.74)  14.388 ms  9.996 ms  11.941 ms
 9  * * *
10  * * *
11  * * *
[...]
30 * * *
```

**Comment by jasonwynn10** [comment]
why can't you just use the existing forums page? https://www.imagicalmine.net/community/

**Comment by Taki21** [comment]
iPocket ur PocketKiller?

**Comment by remotevase** [comment]
@jasonwynn10 why? Duh! If you read ANYTHING during the time when IM transitioned from ImagicalCorp to Inactive-to-Reactive, you would know that IMAGICALMINE COMMUNITY DOES NOT SUPPORT IMAGICALMINE SERVER SOFTWARE IN ANY WAY WHATSOEVER!!!

**Comment by remotevase** [comment]
@iPocket oops, forgot to configure that

**Comment by remotevase** [comment]
@Taki21 that's correct

**Comment by iPocket** [comment]
@Taki21 This is my secret new account... don't tell github about this
please :P

**Comment by iPocket** [comment]
@remotevase I mean, where is the post status page? where is the account details page? the verification email is bugged, in the link they said Have as of Have a good day!

**Comment by remotevase** [comment]
@iPocket things to do:
1. Disable verification email (there: happy?)
Also, are you using mobile or computer? If using mobile, ALWAYS CLICK "full site" as the default mobile theme sucks. If using computer, click on the icon in the top right corner of the screen, then click on your account name, and u will find everything there (if you look around, then on the top right corner of the profile, there will be a little person, and a dropdown menu. Under that dropdown menu should have edit profile. If you don't see any of this, then there is another thing on my Todo list: fix perms

**Comment by iPocket** [comment]
I am always using a Computer (Laptop) I never use mobiles for github.
Also I did not find that "little person".

**Comment by remotevase** [comment]
No, I will disable it, sorry about being unclear there :P

**Comment by remotevase** [comment]
@iPocket no offense, but you are SO BLIND if you dont see the little person. Here is a picture:

**Comment by iPocket** [comment]
I am blind, Lol

**Comment by Taki21** [comment]
lol i wont tell @    github xD

**Comment by Ad5001** [comment]
@remotevase @iPocket Don't mind me but there is no little person. But the is under the gear.

**Comment by remotevase** [comment]
@iPocket :laughing: 
@Ad5001 what? Did you read the conversation **at all?** C'mon, people! You guys gotta start using SCREENSHOTS

**Comment by Ad5001** [comment]
@remotevase I read every single message on commit and conversations.
and if screenshots is what's missing: 
![capture d ecran 65](https://cloud.githubusercontent.com/assets/16436883/17947419/49db3008-6a55-11e6-83ed-71c6e6c7249e.png)

**Comment by remotevase** [comment]
@Ad5001 you gotta click on the "AD5001" thing in the top. Once you get to your profile page, then you see the little person!!!

**Comment by jasonwynn10** [comment]
In case someone cares... the team website was remade! https://inactive-to-reactive.github.io/

**Comment by Taki21** [comment]
wow nice man!

**Comment by remotevase** [comment]
Note TO Self: This user on IM Forums created awesome threads, I gotta add these stuff
https://www.imagicalmine.net/community/members/chris-scalf.1211/

**Comment by TheRoyalBlock** [comment]
Project dead. Click the link in the readme for a new branch. The link is being updated whenever possible so it always remains active some way or another.
