### ISSUE TITLE
ImagicalMine page on website

### ISSUE THREAD

**Issue by jasonwynn10** [Inactive-to-Reactive/ImagicalMine#46]
I remade the IM page on the group website! It looks like it fits the theme of the Homepage now.
https://inactive-to-reactive.github.io/ImagicalMine/
I need someone to add a description of the project and I will add links for the various releases, but otherwise it's done!

**Comment by remotevase** [comment]
@jasonwynn10 no offence, but that doesnt really look that good... See the current website... It is much better suited for ImagicalMine than what you made...

**Comment by jasonwynn10** [comment]
ouch. What do you want done?

**Comment by remotevase** [comment]
Sorry, but the icon doesnt really go well with that background. I think that you should probably make it more "minecraft" themed... Like a nether portal background, or something like that

**Comment by jasonwynn10** [comment]
gimme a bit to work on it

**Comment by remotevase** [comment]
okay! 
In the meanwhile, I will work on the other pages backgrounds. Purple is good for the homepage, but each individual page should have its own background that suits the plugin. EG: Nether portal for ImagicalMine, Magic Wand for MagicalAPI, stuff like that... It just takes a little bit of css editing

**Comment by jasonwynn10** [comment]
ok

**Comment by remotevase** [comment]
I did it!

**Comment by remotevase** [comment]
ImagicalWebsite fixed! I think...

**Comment by remotevase** [comment]
AAH! I messed it up....

**Comment by remotevase** [comment]
I will fix.. U dont do it...

**Comment by dterweij** [comment]
lol is a free minecraft website template :) I use it too.
