### ISSUE TITLE
0.16

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/ImagicalMine#47]
I guess that we are jumping from 0.15 to 0.16! Starting Tuesday, I will work on 0.16 implementation. This tube, I will use a combination of clear sky and steadfast2.
First commit to test: https://github.com/Hydreon/Steadfast2/commit/b70131baa7673d413c57c9369d33b9156f832c25

**Comment by Taki21** [comment]
wow  they commit fast

**Comment by remotevase** [comment]
Ikr

**Comment by remotevase** [comment]
ClearSky has branch, but no commits

**Comment by Sandertv** [comment]
Well let's hope we get it to work this time then.

**Comment by caspervanneck** [comment]
use the genisys branch

**Comment by caspervanneck** [comment]
@remotevase

**Comment by Sandertv** [comment]
I'd not, I think it is a better idea what @remotevase said, so we can add the things of IM too... I also think CS has a little bit better coding.

**Comment by Sandertv** [comment]
So... are we still gonna continue the plan?

**Comment by DarkWav** [comment]
i worked a bit on 0.16.0. you have to test now...

**Comment by DarkWav** [comment]
and of course use the 0.16 branch

**Comment by Sandertv** [comment]
Protocol the same in 0.16?

**Comment by remotevase** [comment]
No. The whole protocol system needs to be rewritten according to MCPE devs

**Comment by thebigsmileXD** [comment]
ImagicalMine (lets call it 3.0) still only has noobs.

**Comment by SOF3** [comment]
Congratulations for posting a copy and paste project on GitHub, a hub of Git, which is a tool used for professional copying and pasting, without Git.

Simple English: Git is essentially a tool for copying and pasting among branches, using a concept called "patches". You arr posting your copy and paste product on GitHub, which is correct, because GitHub is for Git. But congratulations, you are doing what Git is supposed to do automatically on a hub of Git, without using Git.

**Comment by iPocket** [comment]
@SOFe ah

**Comment by Taki21** [comment]
Mojang Literally gave us the protocol every update... in the betas

**Comment by dktapps** [comment]
You attach far too much importance to a meaningless version number.

**Comment by DarkWav** [comment]
Yes the getInt() changed to getVarInt and also some Other getLong() and getShort chnaged.
Sometimes even getUnsignedVarInt()

**Comment by DarkWav** [comment]
Should i do a commit like [this](https://github.com/Inactive-to-Reactive/ImagicalMine/commit/7d2e9fdcd1e92db4e8295db22f5a7b70ef1944cf) commit (i did it once and then reverted it.)

**Comment by Taki21** [comment]
It matters @dktapps anyway i shouldnt be talking im gone for a while bye everyone :(

**Comment by dktapps** [comment]
You attach far too much importance to a meaningless version number.

**Comment by thebigsmileXD** [comment]
And  @SOF3 is, as always, talking around the fact with alot bla and alot blubb.

**Comment by remotevase** [comment]
Time to check if 0.16 branch works!

**Comment by dktapps** [comment]
You attach far too much importance to a meaningless version number.

**Comment by Taki21** [comment]
Please stop i dont attach too much importance on that. maybe u attach too much importance on what u think im so attached to so plz stop!

**Comment by dktapps** [comment]
> Mojang Literally gave us the protocol every update... in the betas

You're nothing but a bunch of leeches. You expect everyone else to do the hard work for you so you can copy it. @remotevase you have a damned nerve opening issues like https://github.com/ClearSkyTeam/ClearSky/issues/725 , like you've done ANY original work whatsoever, or have any understanding of the work you copy-pasted from. ImagicalMine should have stayed dead. PocketMine would be embarrassed to call this sorry group its descendants.

**Comment by SOF3** [comment]
Yeah, ik it's not a lot of importance, you just need a spreadsheet to generate the code.

**Comment by Taki21** [comment]
You shoudn't be TALKING ONE SINGLE BIT. YOU GUYS COPIED STUFF TOO. AND DONT SAY NO.

**Comment by Taki21** [comment]
And we dont do the hardwork? OUR FRIEND @remotevase  has BEEN WORKING HIS SELF OFF JUST TOO CODE AND TEST EVERY POSSIBLE SOLUTION ON HIS COMPUTER FOR US.

**Comment by Taki21** [comment]
And we embarrassed? Please.... Just look at you first. You're talking useless stuff that you guys literally do too.

**Comment by Taki21** [comment]
In fact by calling us leeches ur basically urself a leech, so bye, please stop with your useless non sense.

**Comment by Taki21** [comment]
Ahh thats better no more uselss trash too deal with :p

**Comment by DarkWav** [comment]
lol why do we have an open, and locked issue.
//CLOSED

**Comment by remotevase** [comment]
@Taki21 thanks

**Comment by remotevase** [comment]
time to lock everything!

**Comment by Taki21** [comment]
ya we dont need useless spam garbage and your welcome :p

**Comment by Taki21** [comment]
like the old going says: The Truth HURTS

**Comment by Taki21** [comment]
![56582663](https://cloud.githubusercontent.com/assets/14851895/18805347/17c23760-81d9-11e6-8fe6-65d5c77c1db8.jpg)

**Comment by Taki21** [comment]
I literally laugh at people who think that someone shouldnt do something when they are doing the same thing...
hypocrites in other words... we dont need em
