### ISSUE TITLE
How To stop start.sh in loop mode?

### ISSUE THREAD

**Issue by RedstoneAlmeida** [Inactive-to-Reactive/ImagicalMine#52]
> ## **DO NOT DELETE THE FOLLOWING**
> ### Please Provide the Issue:
> - Edit This Text To Write Your Issue!
> ### Sources:
> - ERROR: Edit This Text To Write Your Issue!
> ### Please provide all that apply to this Issue!
> - [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
> - [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
> - [ ] This issue is written in your native language for maximal clarity
> - [ ] This issue does not have abbreveations. Abbreviations make it not understandable.
> - [ ] This issue is for ImagicalMine, and not any other server software
> - [ ] This is not a suggestion, but an actual issue
> ### Crashdump:
> - Edit This Text To Insert Your Crashdump
> ### Other INFO:
> - How To stop start.sh in loop mode?

**Comment by Sandertv** [comment]
Wait you got it working?

**Comment by Taki21** [comment]
close the main loop window then the rest.

**Comment by RedstoneAlmeida** [comment]
in VPS?

**Comment by Taki21** [comment]
are u using a server provider or u set it up im confused? Because i usually close the loop then close the sever windows :p

**Comment by RedstoneAlmeida** [comment]
I bought a VPN to use it however not of to close it

**Comment by Taki21** [comment]
ohhhh ok let me think about that xD

**Comment by TheRoyalBlock** [comment]
Project dead. Click the link in the readme for a new branch. The link is being updated whenever possible so it always remains active some way or another.
