### ISSUE TITLE
Abandon this project?

### ISSUE THREAD

**Issue by legoboy0215** [Inactive-to-Reactive/ImagicalMine#56]
Seriously, this will never succeed. Official PocketMine is in development again, and Genisys is taking over the majority of PM-spoon users.

**Comment by remotevase** [comment]
i know... Now i help PocketMine again!

**Comment by jasonwynn10** [comment]
I say we close IM officialy

**Comment by remotevase** [comment]
@jasonwynn10 not just yet... I would like to create pull requests that add some IM Features into PM, so don't close the project JUST YET. Wait until all the features are added as PR's into PM

**Comment by jasonwynn10** [comment]
gotcha

**Comment by TheRoyalBlock** [comment]
Project dead. Click the link in the readme for a new branch. The link is being updated whenever possible so it always remains active some way or another.
