### ISSUE TITLE
Blocked for 5 seconds😑

### ISSUE THREAD

**Issue by DarkEtch** [Inactive-to-Reactive/ImagicalMine#61]
[15:51:53] notice> Blocked 192.168.0.10 for 5 seconds

**Comment by DarkEtch** [comment]
When i try to join it log me out and then i go to the control panel and get this!

**Comment by Sandertv** [comment]
Please don't spam this issue, it has already been reported.

**Comment by DarkEtch** [comment]
But this issue have been for 7 days now!
