### ISSUE TITLE
add my to your staff

### ISSUE THREAD

**Issue by caspervanneck** [Inactive-to-Reactive/ImagicalMine#66]
you whand t have 0.16.0 version of ImagicalMine

**Comment by WarenGonzaga** [comment]
What you're saying? They should have the latest version.

**Comment by caspervanneck** [comment]
@WarenGonzaga no you cant join arg

**Comment by WarenGonzaga** [comment]
Join for what?

**Comment by remotevase** [comment]
Join the server

**Comment by WarenGonzaga** [comment]
They still updating it.

**Comment by caspervanneck** [comment]
@remotevase i wanth to try and update it to 1.0.0

**Comment by caspervanneck** [comment]
but can you invite me (or a other owner)

**Comment by remotevase** [comment]
you are a contributor

**Comment by remotevase** [comment]
you are staff!
