### ISSUE TITLE
ImagicalMine Revived!

### ISSUE THREAD

**Issue by ghost** [Inactive-to-Reactive/ImagicalMine#68]
https://github.com/ServerSoftwareArchive/ImagicalMine

**Comment by TheRoyalBlock** [comment]
Sweet!

**Comment by caspervanneck** [comment]
@TheRoyalBlock the new link https://github.com/caspervanneck/ImagicalMine


Why because they delete it

**Comment by iPocket** [comment]
Not really.

**Comment by TheRoyalBlock** [comment]
Yeah, serversoftwarearchive is gone.
