### ISSUE TITLE
Ask Permission

### ISSUE THREAD

**Issue by NycuRO** [Inactive-to-Reactive/ImagicalMine#71]
Hi all.

I'm here for ask for permission @keithkfng and others for:

- Can i use Original Name for ImagicalMine. I'm start with commit https://github.com/Inactive-to-Reactive/ImagicalMine/commit/29872d7f9a1df62977a0d86714742acbad737e9a because this commit have all all codes ImagicalMine without rewites with PocketMine.

- Can i have Banner/Image of ImagicalMine?

I want to create Oldest ImagicalMine for new version and yes, ImagicalMine re-alive 👍

**Comment by TheRoyalBlock** [comment]
I dunno why you would ever want to do this, but sure, go ahead.

**Comment by NycuRO** [comment]
@keithkfng It's ok?

**Comment by TheRoyalBlock** [comment]
How about I give you access to this repository and you commit here?

**Comment by keithkfng** [comment]
Because you're the first one whose asked properly, you have my permission to do so.

**Comment by NycuRO** [comment]
@keithkfng Thanks 👍

**Comment by NycuRO** [comment]
@TheRoyalBlock I create new reposity.
