### ISSUE TITLE
Let's resume the software again.

### ISSUE THREAD

**Issue by shdudwns** [Inactive-to-Reactive/ImagicalMine#72]
Let's resume the software again.

**Comment by shdudwns** [comment]
@Ad5001 @DarkWav

**Comment by TheRoyalBlock** [comment]
AHAHHAGAGGAGAH THATS SO FUNNY

**Comment by shdudwns** [comment]
@TheRoyalBlock why?

**Comment by TheRoyalBlock** [comment]
I'd say it's fully dead. A year is a long time. Try using blueLight instead

**Comment by shdudwns** [comment]
Please contact some developers
I wish the imagicalmine will be revived again.
@TheRoyalBlock

**Comment by TheRoyalBlock** [comment]
None of us developers care enough about ImagicalMine anymore to revive it.
