### ISSUE TITLE
mcpe full relaesed 0.15.0

### ISSUE THREAD

**Issue by lolcraftboy** [Inactive-to-Reactive/ImagicalMine#8]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

**Comment by dterweij** [comment]
Great!

**Comment by remotevase** [comment]
We understand, now we just need the protocol! And a test server!

**Comment by remotevase** [comment]
I will be decompiling the apk after a few moments, and giving my comp. about an hour to search through all of the files for the protocol

**Comment by Taki21** [comment]
??? find protocol like dat???

**Comment by remotevase** [comment]
Yup

**Comment by dterweij** [comment]
Stupid anyway :) why MCPE not just give the changes in a Changelog... it is afterall a change :)

**Comment by remotevase** [comment]
See #9
