### ISSUE TITLE
0.15 Info

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/ImagicalMine#9]
As you all know, 0.15.0.1 is out! Woo hoo, right?! No, not entirely. 
Well, after some testing, at protocol 91 and below, both client and server said outdated server. That means that 91 is definitely outdated. From 92 and above, only the server said outdated, the client tried to connect. This means that 92 is the correct protocol, but there is simply a lack of packets. The next step is to find out which packet is missing, but for now, we know the protocol, so DON'T CHANGE IT!

**Comment by Taki21** [comment]
google search: MiNet Protocol Documentation

**Comment by Mike4l6** [comment]
So.. I can't be seem to find the 0.15 phar is there one or theres not? (In a funny way i think) LELOL

**Comment by dterweij** [comment]
win10 Appstore still shows 0.14.3 here

**Comment by remotevase** [comment]
@Taki21 thanks, kind of helped
@Mike416 the master phar is the 0.15 phar. When the jenkins page is up, it will be there. For now, you can run it from the src by downloading the "src" folder, deleting the old .phar file, then running start.cmd!
@dterweij Oh, thats funny!

**Comment by Mike4l6** [comment]
Wheres the phar file in the src page?

**Comment by mikelees2** [comment]
He probably ment the phar file you are currently using.  I would just move it to another folder just in case.

**Comment by remotevase** [comment]
Follow my instructions!
Download this repository's zip
Unzip it
In your current ImagicalMine folder, delete 1. the ImagicalMine.phar, and 2. The src folder
Copy the src folder from this repo to your current IM Folder
Start the server!

**Comment by TheKnightGamer** [comment]
Protocol is 81

**Comment by remotevase** [comment]
no its not

**Comment by remotevase** [comment]
that's a fact

**Comment by remotevase** [comment]
0.14.99.3 had a protocol of 81, not 0.15.0.1

**Comment by Ad5001** [comment]
Guys, they made changes about the protocol system.
It's now DYNAMIC !

**Comment by Sandertv** [comment]
Oh god let the fun begin -.-

**Comment by TheKnightGamer** [comment]
I will look around mcpe files

**Comment by Mike4l6** [comment]
When I unzip it I started it and it was still 0.14.x :/ I'll just wait for the phar for 0.15
